/**
 * Account deletion inventory (iOS paywall Task 6) — the classification the routine
 * (supabase/migrations/*_account_deletion_routine.sql), the FK guard test and
 * plans/ios-paywall/deletion-inventory.md share. A new FK into a covered parent fails
 * tests/account-deletion-postgres.test.ts until it is listed and classified here.
 */

/** Retention per A2; mirrors private.account_deletion_retention(). */
export const ACCOUNT_DELETION_RETENTION = {
  billing: "10 years",
  cancellation_evidence: "3 years",
} as const

export type AccountDeletionTableClass =
  | "cascade"
  | "delete"
  | "anonymize_billing"
  | "anonymize_cancellation_evidence"
  | "keep_anonymous"
  | "no_personal_data"

export const ACCOUNT_DELETION_COVERED_PARENTS = [
  "auth.users",
  "public.profiles",
  "public.leads",
  "public.funnel_sessions",
  "public.trial_enrollments",
  "public.billing_one_time_purchases",
  "public.product_submissions",
] as const

export const ACCOUNT_DELETION_TABLE_CLASSES: Readonly<Record<string, AccountDeletionTableClass>> = {
  "private.mobile_push_installations": "cascade",
  "private.mobile_research_deliveries": "cascade",
  "private.mobile_research_delivery_candidates": "cascade",
  "private.slack_growth_edge_leases": "cascade",
  "public.app_store_subscription_status": "cascade",
  "public.app_store_transactions": "cascade",
  "public.billing_analytics_deliveries": "cascade",
  "public.billing_analytics_outbox": "cascade",
  "public.billing_subscription_plan_changes": "cascade",
  "public.billing_subscriptions": "cascade",
  "public.checkout_activation_claims": "cascade",
  "public.conversation_states": "cascade",
  "public.conversation_turn_traces": "cascade",
  "public.conversations": "cascade",
  "public.discovery_call_decisions": "cascade",
  "public.discovery_intake_items": "cascade",
  "public.discovery_intakes": "cascade",
  "public.dismissed_suggestions": "cascade",
  "public.freemium_plan_admissions": "cascade",
  "public.hair_profiles": "cascade",
  "public.membership_reactivation_checkout_reservations": "cascade",
  "public.messages": "cascade",
  "public.mobile_registration_enrollments": "cascade",
  "public.mobile_registration_publication_receipts": "cascade",
  "public.mobile_scan_history": "cascade",
  "public.partner_access_email_changes": "cascade",
  "public.personal_plan_migration_enrollments": "cascade",
  "public.personal_plan_need_versions": "cascade",
  "public.personal_plan_portfolio_versions": "cascade",
  "public.personal_plan_product_drafts": "cascade",
  "public.personal_plan_refinement_drafts": "cascade",
  "public.personal_plan_routine_proposals": "cascade",
  "public.personal_plan_routine_source_change_outbox": "cascade",
  "public.personal_plan_routine_versions": "cascade",
  "public.personal_plan_ui_lifecycle_marks": "cascade",
  "public.personal_plans": "cascade",
  "public.profiles": "cascade",
  "public.routine_log_products": "cascade",
  "public.routine_logs": "cascade",
  "public.scan_free_reveals": "cascade",
  "public.scan_wishlist": "cascade",
  "public.scanner_context_heads": "cascade",
  "public.scanner_context_sources": "cascade",
  "public.scanner_context_versions": "cascade",
  "public.scanner_paid_source_bindings": "cascade",
  "public.scanner_profile_edit_receipts": "cascade",
  "public.scanner_profile_edits": "cascade",
  "public.tracker_nudge_dismissals": "cascade",
  "public.user_memory_entries": "cascade",
  "public.user_memory_settings": "cascade",
  "public.user_products": "cascade",
  "public.waitlist_customerio_outbox": "cascade",
  "auth.audit_log_entries": "delete",
  "auth.users": "delete",
  "private.openai_ads_contexts": "delete",
  "public.beta_feedback": "delete",
  "public.customerio_profile_sync_outbox": "delete",
  "public.discovery_enrollments": "delete",
  "public.funnel_events": "delete",
  "public.manual_access_grants": "delete",
  "public.mobile_auth_attempts": "delete",
  "public.mobile_registration_intents": "delete",
  "public.partner_access_invitations": "delete",
  "public.personal_plan_prepared_artifacts": "delete",
  "public.personal_plan_quiz_drafts": "delete",
  "public.personal_plan_result_returns": "delete",
  "public.personal_plan_test_enrollments": "delete",
  "public.personal_plan_test_members": "delete",
  "public.quiz_email_return_links": "delete",
  "public.rate_limits": "delete",
  "public.regular_quiz_test_enrollments": "delete",
  "public.user_product_usage": "delete",
  "public.waitlist_signups": "delete",
  "private.paypal_trial_activation_evidence": "anonymize_billing",
  "private.paypal_trial_checkout_attempts": "anonymize_billing",
  "private.paypal_trial_management_requests": "anonymize_billing",
  "private.paypal_trial_paid_recovery_requests": "anonymize_billing",
  "private.paypal_trial_plan_catalogs": "anonymize_billing",
  "private.stripe_trial_continuation_operations": "anonymize_billing",
  "private.stripe_trial_management_approvals": "anonymize_billing",
  "private.stripe_trial_paid_recovery_requests": "anonymize_billing",
  "private.trial_analytics_contexts": "anonymize_billing",
  "private.trial_management_agreement_bindings": "anonymize_billing",
  "private.trial_management_catalogs": "anonymize_billing",
  "private.trial_management_operations": "anonymize_billing",
  "private.trial_management_state": "anonymize_billing",
  "private.trial_offer_revisions": "anonymize_billing",
  "private.trial_paid_continuation_history": "anonymize_billing",
  "private.trial_paid_continuations": "anonymize_billing",
  "private.trial_paid_recovery_operations": "anonymize_billing",
  "private.trial_payment_continuation_reconciliations": "anonymize_billing",
  "private.trial_payment_events": "anonymize_billing",
  "public.billing_one_time_purchases": "anonymize_billing",
  "public.funnel_sessions": "anonymize_billing",
  "public.leads": "anonymize_billing",
  "public.paypal_checkout_intents": "anonymize_billing",
  "public.paypal_expired_order_reset_audit": "anonymize_billing",
  "public.paypal_order_intents": "anonymize_billing",
  "public.personal_plan_one_time_checkout_consents": "anonymize_billing",
  "public.personal_plan_one_time_fulfillment_jobs": "anonymize_billing",
  "public.trial_checkout_attempts": "anonymize_billing",
  "public.trial_enrollments": "anonymize_billing",
  "private.public_contract_declaration_applications": "anonymize_cancellation_evidence",
  "private.public_contract_declaration_completions": "anonymize_cancellation_evidence",
  "private.public_contract_declaration_matches": "anonymize_cancellation_evidence",
  "private.public_contract_declaration_receipts": "anonymize_cancellation_evidence",
  "private.public_contract_declaration_reviews": "anonymize_cancellation_evidence",
  "private.public_contract_declarations": "anonymize_cancellation_evidence",
  "private.stripe_paid_cancellation_operations": "anonymize_cancellation_evidence",
  "private.trial_cancellation_declarations": "anonymize_cancellation_evidence",
  "private.trial_cancellation_provider_operations": "anonymize_cancellation_evidence",
  "private.trial_cancellation_receipts": "anonymize_cancellation_evidence",
  "private.trial_identity_sources": "anonymize_cancellation_evidence",
  "private.trial_paid_cancellation_declarations": "anonymize_cancellation_evidence",
  "private.trial_reminders": "anonymize_cancellation_evidence",
  "private.trial_required_notices": "anonymize_cancellation_evidence",
  "public.payment_support_cases": "anonymize_cancellation_evidence",
  "public.trial_identity_claims": "anonymize_cancellation_evidence",
  "public.product_submissions": "keep_anonymous",
  "public.scan_resolve_events": "keep_anonymous",
  "private.trial_identity_restrictions": "no_personal_data",
  "public.billing_webhook_events": "no_personal_data",
  "public.product_intake_research_artifacts": "no_personal_data",
  "public.product_intake_research_jobs": "no_personal_data",
  "public.product_intake_review_decisions": "no_personal_data",
}

/** Every FK into the covered parents (transitively), with its delete action. */
export const ACCOUNT_DELETION_FK_EDGES: readonly string[] = [
  "private.mobile_push_installations(user_id) -> public.profiles [cascade]",
  "private.mobile_research_deliveries(submission_id) -> public.product_submissions [cascade]",
  "private.mobile_research_deliveries(user_id) -> public.profiles [cascade]",
  "private.mobile_research_delivery_candidates(submission_id) -> public.product_submissions [cascade]",
  "private.mobile_research_delivery_candidates(user_id) -> public.profiles [cascade]",
  "private.openai_ads_contexts(session_id) -> public.funnel_sessions [cascade]",
  "private.paypal_trial_activation_evidence(attempt_id) -> private.paypal_trial_checkout_attempts [restrict]",
  "private.paypal_trial_checkout_attempts(intent_id) -> public.paypal_checkout_intents [restrict]",
  "private.paypal_trial_checkout_attempts(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.paypal_trial_management_requests(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.paypal_trial_paid_recovery_requests(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.paypal_trial_plan_catalogs(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.public_contract_declaration_applications(trial_declaration_id) -> private.trial_cancellation_declarations [restrict]",
  "private.public_contract_declaration_matches(user_id) -> public.profiles [set_null]",
  "private.public_contract_declaration_matches(enrollment_id) -> public.trial_enrollments [set_null]",
  "private.slack_growth_edge_leases(delivery_id) -> public.billing_analytics_deliveries [cascade]",
  "private.stripe_paid_cancellation_operations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.stripe_trial_continuation_operations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.stripe_trial_management_approvals(operation_id) -> private.trial_management_operations [restrict]",
  "private.stripe_trial_paid_recovery_requests(operation_id) -> private.trial_paid_recovery_operations [restrict]",
  "private.trial_analytics_contexts(enrollment_id) -> public.trial_enrollments [cascade]",
  "private.trial_cancellation_declarations(user_id) -> public.profiles [set_null]",
  "private.trial_cancellation_declarations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_cancellation_provider_operations(declaration_id) -> private.trial_cancellation_declarations [restrict]",
  "private.trial_cancellation_receipts(declaration_id) -> private.trial_cancellation_declarations [restrict]",
  "private.trial_cancellation_receipts(user_id) -> public.profiles [set_null]",
  "private.trial_identity_restrictions(enrollment_id) -> public.trial_enrollments [set_null]",
  "private.trial_management_agreement_bindings(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_management_catalogs(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_management_operations(user_id) -> public.profiles [set_null]",
  "private.trial_management_operations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_management_state(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_offer_revisions(operation_id) -> private.trial_management_operations [restrict]",
  "private.trial_offer_revisions(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_paid_cancellation_declarations(user_id) -> public.profiles [set_null]",
  "private.trial_paid_cancellation_declarations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_paid_continuation_history(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_paid_continuations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_paid_recovery_operations(user_id) -> public.profiles [set_null]",
  "private.trial_paid_recovery_operations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_payment_continuation_reconciliations(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_payment_events(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_reminders(user_id) -> public.profiles [set_null]",
  "private.trial_reminders(enrollment_id) -> public.trial_enrollments [restrict]",
  "private.trial_required_notices(declaration_id) -> private.trial_cancellation_declarations [set_null]",
  "private.trial_required_notices(user_id) -> public.profiles [set_null]",
  "private.trial_required_notices(enrollment_id) -> public.trial_enrollments [set_null]",
  "public.app_store_subscription_status(user_id) -> public.profiles [cascade]",
  "public.app_store_transactions(user_id) -> public.profiles [cascade]",
  "public.beta_feedback(user_id) -> auth.users [set_null]",
  "public.billing_analytics_deliveries(outbox_id) -> public.billing_analytics_outbox [cascade]",
  "public.billing_analytics_outbox(user_id) -> public.profiles [cascade]",
  "public.billing_one_time_purchases(consent_id) -> public.personal_plan_one_time_checkout_consents [restrict]",
  "public.billing_one_time_purchases(user_id) -> public.profiles [restrict]",
  "public.billing_subscription_plan_changes(billing_subscription_id) -> public.billing_subscriptions [cascade]",
  "public.billing_subscription_plan_changes(user_id) -> public.profiles [cascade]",
  "public.billing_subscriptions(user_id) -> public.profiles [cascade]",
  "public.billing_subscriptions(trial_enrollment_id) -> public.trial_enrollments [restrict]",
  "public.checkout_activation_claims(user_id) -> auth.users [cascade]",
  "public.conversation_states(conversation_id) -> public.conversations [cascade]",
  "public.conversation_states(conversation_id,user_id) -> public.conversations [no_action]",
  "public.conversation_states(user_id) -> public.profiles [cascade]",
  "public.conversation_turn_traces(conversation_id) -> public.conversations [set_null]",
  "public.conversation_turn_traces(assistant_message_id) -> public.messages [set_null]",
  "public.conversation_turn_traces(user_message_id) -> public.messages [set_null]",
  "public.conversation_turn_traces(user_id) -> public.profiles [cascade]",
  "public.conversations(user_id) -> public.profiles [cascade]",
  "public.customerio_profile_sync_outbox(lead_id) -> public.leads [cascade]",
  "public.discovery_call_decisions(intake_item_id) -> public.discovery_intake_items [cascade]",
  "public.discovery_call_decisions(intake_id) -> public.discovery_intakes [cascade]",
  "public.discovery_enrollments(claimed_user_id) -> public.profiles [restrict]",
  "public.discovery_intake_items(intake_id) -> public.discovery_intakes [cascade]",
  "public.discovery_intake_items(product_submission_id) -> public.product_submissions [set_null]",
  "public.discovery_intakes(enrollment_id) -> public.discovery_enrollments [cascade]",
  "public.discovery_intakes(user_id) -> public.profiles [cascade]",
  "public.dismissed_suggestions(user_id) -> public.profiles [cascade]",
  "public.freemium_plan_admissions(user_id) -> auth.users [cascade]",
  "public.freemium_plan_admissions(lead_id) -> public.leads [restrict]",
  "public.funnel_events(funnel_session_id) -> public.funnel_sessions [cascade]",
  "public.funnel_events(lead_id) -> public.leads [set_null]",
  "public.funnel_sessions(lead_id) -> public.leads [set_null]",
  "public.funnel_sessions(partner_access_invitation_id) -> public.partner_access_invitations [restrict]",
  "public.funnel_sessions(user_id) -> public.profiles [set_null]",
  "public.hair_profiles(user_id) -> public.profiles [cascade]",
  "public.leads(partner_access_invitation_id) -> public.partner_access_invitations [restrict]",
  "public.leads(user_id) -> public.profiles [set_null]",
  "public.manual_access_grants(partner_access_invitation_id) -> public.partner_access_invitations [restrict]",
  "public.manual_access_grants(user_id) -> public.profiles [cascade]",
  "public.membership_reactivation_checkout_reservations(user_id) -> public.profiles [cascade]",
  "public.messages(conversation_id) -> public.conversations [cascade]",
  "public.mobile_registration_enrollments(user_id) -> public.profiles [cascade]",
  "public.mobile_registration_publication_receipts(user_id) -> public.profiles [cascade]",
  "public.mobile_scan_history(submission_id) -> public.product_submissions [set_null]",
  "public.mobile_scan_history(user_id) -> public.profiles [cascade]",
  "public.partner_access_email_changes(invitation_id) -> public.partner_access_invitations [cascade]",
  "public.partner_access_invitations(funnel_session_id) -> public.funnel_sessions [restrict]",
  "public.partner_access_invitations(lead_id) -> public.leads [restrict]",
  "public.partner_access_invitations(current_manual_access_grant_id) -> public.manual_access_grants [restrict]",
  "public.partner_access_invitations(claimed_user_id) -> public.profiles [restrict]",
  "public.partner_access_invitations(created_by_user_id) -> public.profiles [set_null]",
  "public.payment_support_cases(lead_id) -> public.leads [no_action]",
  "public.payment_support_cases(resolved_by) -> public.profiles [no_action]",
  "public.payment_support_cases(user_id) -> public.profiles [no_action]",
  "public.paypal_checkout_intents(reactivation_reservation_id) -> public.membership_reactivation_checkout_reservations [set_null]",
  "public.paypal_checkout_intents(user_id) -> public.profiles [set_null]",
  "public.paypal_expired_order_reset_audit(intent_id) -> public.paypal_order_intents [restrict]",
  "public.paypal_expired_order_reset_audit(consent_id) -> public.personal_plan_one_time_checkout_consents [restrict]",
  "public.paypal_order_intents(funnel_session_id) -> public.funnel_sessions [restrict]",
  "public.paypal_order_intents(lead_id) -> public.leads [restrict]",
  "public.paypal_order_intents(consent_id) -> public.personal_plan_one_time_checkout_consents [restrict]",
  "public.paypal_order_intents(user_id) -> public.profiles [set_null]",
  "public.personal_plan_migration_enrollments(lead_id) -> public.leads [restrict]",
  "public.personal_plan_migration_enrollments(user_id) -> public.profiles [cascade]",
  "public.personal_plan_need_versions(stage1_source_lead_id) -> public.leads [restrict]",
  "public.personal_plan_need_versions(parent_need_version_id,user_id,personal_plan_id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plan_need_versions(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_need_versions(user_id) -> public.profiles [cascade]",
  "public.personal_plan_one_time_checkout_consents(funnel_session_id) -> public.funnel_sessions [restrict]",
  "public.personal_plan_one_time_checkout_consents(lead_id) -> public.leads [restrict]",
  "public.personal_plan_one_time_checkout_consents(user_id) -> public.profiles [restrict]",
  "public.personal_plan_one_time_fulfillment_jobs(purchase_id) -> public.billing_one_time_purchases [restrict]",
  "public.personal_plan_one_time_fulfillment_jobs(consent_id) -> public.personal_plan_one_time_checkout_consents [restrict]",
  "public.personal_plan_portfolio_versions(refined_need_version_id,user_id,personal_plan_id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plan_portfolio_versions(parent_portfolio_version_id,user_id,personal_plan_id) -> public.personal_plan_portfolio_versions [restrict]",
  "public.personal_plan_portfolio_versions(lineage_product_draft_id,user_id,personal_plan_id) -> public.personal_plan_product_drafts [restrict]",
  "public.personal_plan_portfolio_versions(source_product_draft_id,user_id,personal_plan_id) -> public.personal_plan_product_drafts [restrict]",
  "public.personal_plan_portfolio_versions(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_portfolio_versions(user_id) -> public.profiles [cascade]",
  "public.personal_plan_prepared_artifacts(user_id) -> auth.users [set_null]",
  "public.personal_plan_prepared_artifacts(lead_id) -> public.leads [cascade]",
  "public.personal_plan_prepared_artifacts(superseded_by) -> public.personal_plan_prepared_artifacts [set_null]",
  "public.personal_plan_product_drafts(refined_need_version_id,user_id,personal_plan_id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plan_product_drafts(repair_source_product_draft_id,user_id,personal_plan_id) -> public.personal_plan_product_drafts [restrict]",
  "public.personal_plan_product_drafts(repair_source_routine_version_id,user_id,personal_plan_id) -> public.personal_plan_routine_versions [restrict]",
  "public.personal_plan_product_drafts(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_product_drafts(user_id) -> public.profiles [cascade]",
  "public.personal_plan_quiz_drafts(funnel_session_id) -> public.funnel_sessions [restrict]",
  "public.personal_plan_refinement_drafts(base_initial_need_version_id,user_id,personal_plan_id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plan_refinement_drafts(result_refined_need_version_id,user_id,personal_plan_id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plan_refinement_drafts(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_refinement_drafts(user_id) -> public.profiles [cascade]",
  "public.personal_plan_result_returns(lead_id) -> public.leads [cascade]",
  "public.personal_plan_routine_proposals(base_routine_version_id,user_id,personal_plan_id) -> public.personal_plan_routine_versions [restrict]",
  "public.personal_plan_routine_proposals(candidate_routine_version_id,user_id,personal_plan_id) -> public.personal_plan_routine_versions [restrict]",
  "public.personal_plan_routine_proposals(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_routine_proposals(user_id) -> public.profiles [cascade]",
  "public.personal_plan_routine_source_change_outbox(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_routine_source_change_outbox(user_id) -> public.profiles [cascade]",
  "public.personal_plan_routine_versions(source_refined_need_version_id,user_id,personal_plan_id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plan_routine_versions(source_portfolio_version_id,user_id,personal_plan_id) -> public.personal_plan_portfolio_versions [restrict]",
  "public.personal_plan_routine_versions(source_product_draft_id,user_id,personal_plan_id) -> public.personal_plan_product_drafts [restrict]",
  "public.personal_plan_routine_versions(parent_routine_version_id,user_id,personal_plan_id) -> public.personal_plan_routine_versions [restrict]",
  "public.personal_plan_routine_versions(personal_plan_id,user_id) -> public.personal_plans [restrict]",
  "public.personal_plan_routine_versions(user_id) -> public.profiles [cascade]",
  "public.personal_plan_test_enrollments(user_id) -> auth.users [restrict]",
  "public.personal_plan_test_enrollments(funnel_session_id) -> public.funnel_sessions [restrict]",
  "public.personal_plan_test_enrollments(lead_id) -> public.leads [restrict]",
  "public.personal_plan_test_enrollments(manual_access_grant_id) -> public.manual_access_grants [restrict]",
  "public.personal_plan_test_enrollments(prepared_artifact_id) -> public.personal_plan_prepared_artifacts [restrict]",
  "public.personal_plan_test_members(user_id) -> auth.users [restrict]",
  "public.personal_plan_test_members(enrollment_id) -> public.personal_plan_test_enrollments [restrict]",
  "public.personal_plan_ui_lifecycle_marks(user_id) -> auth.users [cascade]",
  "public.personal_plans(current_initial_need_version_id,user_id,id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plans(current_refined_need_version_id,user_id,id) -> public.personal_plan_need_versions [restrict]",
  "public.personal_plans(pending_routine_proposal_id,user_id,id) -> public.personal_plan_routine_proposals [restrict]",
  "public.personal_plans(active_routine_version_id,user_id,id) -> public.personal_plan_routine_versions [restrict]",
  "public.personal_plans(user_id) -> public.profiles [cascade]",
  "public.product_intake_research_artifacts(job_id) -> public.product_intake_research_jobs [set_null]",
  "public.product_intake_research_artifacts(submission_id) -> public.product_submissions [cascade]",
  "public.product_intake_research_jobs(submission_id) -> public.product_submissions [cascade]",
  "public.product_intake_review_decisions(job_id) -> public.product_intake_research_jobs [set_null]",
  "public.product_intake_review_decisions(submission_id) -> public.product_submissions [cascade]",
  "public.product_submissions(source_conversation_id,user_id) -> public.conversations [set_null]",
  "public.product_submissions(user_id) -> public.profiles [cascade]",
  "public.product_submissions(user_product_usage_id,user_id,category) -> public.user_product_usage [set_null]",
  "public.product_submissions(user_product_id,user_id,category) -> public.user_products [restrict]",
  "public.profiles(id) -> auth.users [cascade]",
  "public.quiz_email_return_links(source_lead_id) -> public.leads [cascade]",
  "public.regular_quiz_test_enrollments(user_id) -> auth.users [restrict]",
  "public.regular_quiz_test_enrollments(funnel_session_id) -> public.funnel_sessions [restrict]",
  "public.regular_quiz_test_enrollments(lead_id) -> public.leads [restrict]",
  "public.regular_quiz_test_enrollments(manual_access_grant_id) -> public.manual_access_grants [restrict]",
  "public.routine_log_products(routine_log_id) -> public.routine_logs [cascade]",
  "public.routine_log_products(user_product_usage_id) -> public.user_product_usage [set_null]",
  "public.routine_logs(user_id) -> public.profiles [cascade]",
  "public.scan_free_reveals(user_id) -> auth.users [cascade]",
  "public.scan_resolve_events(user_id) -> auth.users [cascade]",
  "public.scan_wishlist(user_id) -> auth.users [cascade]",
  "public.scanner_context_heads(user_id) -> public.profiles [cascade]",
  "public.scanner_context_heads(context_version_id,user_id) -> public.scanner_context_versions [no_action]",
  "public.scanner_context_sources(user_id) -> public.profiles [cascade]",
  "public.scanner_context_versions(user_id) -> public.profiles [cascade]",
  "public.scanner_paid_source_bindings(need_version_id) -> public.personal_plan_need_versions [cascade]",
  "public.scanner_paid_source_bindings(user_id) -> public.profiles [cascade]",
  "public.scanner_profile_edit_receipts(user_id) -> public.profiles [cascade]",
  "public.scanner_profile_edits(user_id) -> public.profiles [cascade]",
  "public.scanner_profile_edits(context_version_id,user_id) -> public.scanner_context_versions [no_action]",
  "public.tracker_nudge_dismissals(user_id) -> public.profiles [cascade]",
  "public.trial_checkout_attempts(enrollment_id) -> public.trial_enrollments [restrict]",
  "public.trial_enrollments(user_id) -> public.profiles [set_null]",
  "public.trial_identity_claims(enrollment_id) -> public.trial_enrollments [set_null]",
  "public.user_memory_entries(source_conversation_id) -> public.conversations [cascade]",
  "public.user_memory_entries(user_id) -> public.profiles [cascade]",
  "public.user_memory_entries(superseded_by) -> public.user_memory_entries [set_null]",
  "public.user_memory_settings(user_id) -> public.profiles [cascade]",
  "public.user_product_usage(product_submission_id,user_id,category) -> public.product_submissions [set_null]",
  "public.user_product_usage(user_id) -> public.profiles [cascade]",
  "public.user_products(user_id) -> public.profiles [cascade]",
]
