#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import process from "node:process"
import { fileURLToPath, pathToFileURL } from "node:url"

const KEY_PATTERN = /^[a-z0-9]+(?:_[a-z0-9]+)*$/
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const PROPERTY_KEY_PATTERN = /^[a-z_$][a-z0-9_$]*$/i
const CHANNELS = new Set(["organic", "meta", "internal"])
const STATUSES = new Set(["active", "placeholder", "archived"])
const ARGUMENT_NAMES = new Set(["key", "slug", "landing", "quiz", "offer", "channel", "status"])

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const defaultRoot = path.resolve(scriptDirectory, "../..")

function usage() {
  return `Usage:
  npm run funnel:new -- --key <package_key> --slug <landing-slug> --landing <variant> --quiz <registered-quiz-variant> --offer <variant> [--channel meta] [--status placeholder]
  npm run funnel:check

Registered quiz variants:
  legacy-quiz-v1 (quiz kind: legacy; shared /quiz delivery; default landing)
  personal-plan-quiz-v1 (quiz kind: personal_plan; embedded personal-plan-quiz landing)`
}

export function parseFunnelArgs(argv) {
  const values = {}
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === "--help" || arg === "-h") return { help: true }
    if (!arg.startsWith("--")) throw new Error(`Unexpected argument: ${arg}`)
    const name = arg.slice(2)
    if (!ARGUMENT_NAMES.has(name)) throw new Error(`Unknown argument: --${name}`)
    const value = argv[index + 1]
    if (!value || value.startsWith("--")) throw new Error(`Missing value for --${name}`)
    values[name] = value
    index += 1
  }

  return {
    key: values.key,
    slug: values.slug,
    landingVariant: values.landing,
    quizVariant: values.quiz,
    offerVariant: values.offer,
    channel: values.channel ?? "meta",
    status: values.status ?? "placeholder",
  }
}

function assertPackageInput(input) {
  for (const [name, value] of Object.entries({
    key: input.key,
    slug: input.slug,
    landing: input.landingVariant,
    quiz: input.quizVariant,
    offer: input.offerVariant,
  })) {
    if (!value) throw new Error(`Missing required --${name}`)
  }
  if (!KEY_PATTERN.test(input.key)) throw new Error("Package key must use snake_case")
  if (!SLUG_PATTERN.test(input.slug)) throw new Error("Slug must use kebab-case")
  if (!SLUG_PATTERN.test(input.landingVariant)) {
    throw new Error("Landing variant must use kebab-case")
  }
  if (!SLUG_PATTERN.test(input.offerVariant)) throw new Error("Offer variant must use kebab-case")
  if (!CHANNELS.has(input.channel)) throw new Error(`Unsupported channel: ${input.channel}`)
  if (!STATUSES.has(input.status)) throw new Error(`Unsupported status: ${input.status}`)
}

function toComponentName(value) {
  return value
    .split("-")
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("")
}

function toPropertyKey(value) {
  return PROPERTY_KEY_PATTERN.test(value) ? value : JSON.stringify(value)
}

function listVariantIds(directory) {
  if (!existsSync(directory)) return []
  return readdirSync(directory)
    .filter((name) => name.endsWith(".tsx"))
    .map((name) => name.slice(0, -4))
    .sort()
}

function buildLandingRegistry(ids) {
  const imports = ids.map((id, index) => `import LandingVariant${index} from "./${id}"`).join("\n")
  const entries = ids
    .map((id, index) => `  ${toPropertyKey(id)}: LandingVariant${index},`)
    .join("\n")
  return `// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.\n${imports}\n\nexport const LANDING_VARIANTS = {\n${entries}\n} as const\n`
}

function buildOfferRegistry(ids) {
  const imports = ids.map((id, index) => `import OfferVariant${index} from "./${id}"`).join("\n")
  const entries = ids.map((id, index) => `  ${toPropertyKey(id)}: OfferVariant${index},`).join("\n")
  return `"use client"\n\n// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.\n${imports}\n\nexport const OFFER_VARIANTS = {\n${entries}\n} as const\n`
}

function landingTemplate(id) {
  return `import DefaultLandingVariant from "./default"\n\nexport default function Funnel${toComponentName(id)}LandingVariant() {\n  return <DefaultLandingVariant />\n}\n`
}

function offerTemplate(id) {
  return `"use client"\n\nimport DefaultOfferVariant from "./default"\nimport type { FunnelOfferVariantProps } from "@/funnels/types"\n\nexport default function Funnel${toComponentName(id)}OfferVariant(props: FunnelOfferVariantProps) {\n  return <DefaultOfferVariant {...props} />\n}\n`
}

function funnelPaths(rootDir) {
  const funnelDirectory = path.join(rootDir, "src/funnels")
  return {
    packages: path.join(funnelDirectory, "packages.json"),
    quizRegistry: path.join(funnelDirectory, "quizzes/registry.json"),
    landingDirectory: path.join(funnelDirectory, "landing"),
    landingRegistry: path.join(funnelDirectory, "landing/registry.generated.ts"),
    offerDirectory: path.join(funnelDirectory, "offers"),
    offerRegistry: path.join(funnelDirectory, "offers/registry.generated.ts"),
  }
}

function readQuizVariants(quizRegistryPath) {
  const quizVariants = JSON.parse(readFileSync(quizRegistryPath, "utf8"))
  if (!Array.isArray(quizVariants)) {
    throw new Error("src/funnels/quizzes/registry.json must contain a list")
  }
  const ids = new Set()
  for (const quizVariant of quizVariants) {
    if (!quizVariant || typeof quizVariant !== "object") {
      throw new Error("Quiz variant registry entries must be objects")
    }
    if (typeof quizVariant.id !== "string" || !SLUG_PATTERN.test(quizVariant.id)) {
      throw new Error(`Invalid quiz variant ID: ${String(quizVariant.id)}`)
    }
    if (ids.has(quizVariant.id)) throw new Error(`Duplicate quiz variant ID: ${quizVariant.id}`)
    ids.add(quizVariant.id)
    if (!["legacy", "personal_plan"].includes(quizVariant.quizKind)) {
      throw new Error(`Unsupported quiz kind: ${String(quizVariant.quizKind)}`)
    }
    if (
      !Array.isArray(quizVariant.landingVariants) ||
      quizVariant.landingVariants.length === 0 ||
      quizVariant.landingVariants.some((landingVariant) =>
        typeof landingVariant !== "string" || !SLUG_PATTERN.test(landingVariant),
      )
    ) {
      throw new Error(`Invalid landing variants for quiz variant: ${quizVariant.id}`)
    }
    if (!quizVariant.delivery || typeof quizVariant.delivery !== "object") {
      throw new Error(`Invalid quiz delivery seam for quiz variant: ${quizVariant.id}`)
    }
    if (quizVariant.delivery.kind === "route" && quizVariant.delivery.route === "/quiz") continue
    if (
      quizVariant.delivery.kind === "embedded" &&
      typeof quizVariant.delivery.landingVariant === "string" &&
      quizVariant.landingVariants.includes(quizVariant.delivery.landingVariant)
    ) {
      continue
    }
    throw new Error(`Invalid quiz delivery seam for quiz variant: ${quizVariant.id}`)
  }
  return quizVariants
}

function assertRegisteredQuizVariant(input, quizVariants) {
  const quizVariant = quizVariants.find((item) => item.id === input.quizVariant)
  if (!quizVariant) throw new Error(`Unknown quiz variant: ${input.quizVariant}`)
  const isEmbeddedLanding = quizVariants.some(
    (candidate) =>
      candidate.delivery.kind === "embedded" && candidate.delivery.landingVariant === input.landingVariant,
  )
  const isCompatible =
    quizVariant.delivery.kind === "route"
      ? !isEmbeddedLanding
      : quizVariant.landingVariants.includes(input.landingVariant)
  if (!isCompatible) {
    throw new Error(
      `Quiz variant ${input.quizVariant} is not compatible with landing variant ${input.landingVariant}`,
    )
  }
  return quizVariant
}

function readPackages(packagePath) {
  const packages = JSON.parse(readFileSync(packagePath, "utf8"))
  if (!Array.isArray(packages)) throw new Error("src/funnels/packages.json must contain a list")
  return packages
}

export function expectedFunnelRegistries(rootDir = defaultRoot) {
  const paths = funnelPaths(rootDir)
  return {
    landingIds: listVariantIds(paths.landingDirectory),
    offerIds: listVariantIds(paths.offerDirectory),
    landingSource: buildLandingRegistry(listVariantIds(paths.landingDirectory)),
    offerSource: buildOfferRegistry(listVariantIds(paths.offerDirectory)),
  }
}

export function checkFunnelFiles(rootDir = defaultRoot) {
  const paths = funnelPaths(rootDir)
  const expected = expectedFunnelRegistries(rootDir)
  const packages = readPackages(paths.packages)
  const quizVariants = readQuizVariants(paths.quizRegistry)
  const errors = []

  if (readFileSync(paths.landingRegistry, "utf8") !== expected.landingSource) {
    errors.push("Landing registry is stale; run npm run funnel:check -- --write")
  }
  if (readFileSync(paths.offerRegistry, "utf8") !== expected.offerSource) {
    errors.push("Offer registry is stale; run npm run funnel:check -- --write")
  }

  for (const funnelPackage of packages) {
    if (!expected.landingIds.includes(funnelPackage.landingVariant)) {
      errors.push(`${funnelPackage.key} references missing landing ${funnelPackage.landingVariant}`)
    }
    try {
      assertRegisteredQuizVariant(funnelPackage, quizVariants)
    } catch (error) {
      errors.push(error instanceof Error ? `${funnelPackage.key}: ${error.message}` : `${funnelPackage.key}: invalid quiz variant`)
    }
    if (!expected.offerIds.includes(funnelPackage.offerVariant)) {
      errors.push(`${funnelPackage.key} references missing offer ${funnelPackage.offerVariant}`)
    }
  }

  if (errors.length > 0) throw new Error(errors.join("\n"))
  return expected
}

export function writeFunnelRegistries(rootDir = defaultRoot) {
  const paths = funnelPaths(rootDir)
  const expected = expectedFunnelRegistries(rootDir)
  writeFileSync(paths.landingRegistry, expected.landingSource)
  writeFileSync(paths.offerRegistry, expected.offerSource)
  return expected
}

export function createFunnelPackage(input, rootDir = defaultRoot) {
  assertPackageInput(input)
  const paths = funnelPaths(rootDir)
  const packages = readPackages(paths.packages)
  const quizVariants = readQuizVariants(paths.quizRegistry)
  const quizVariant = assertRegisteredQuizVariant(input, quizVariants)
  if (packages.some((item) => item.key === input.key)) {
    throw new Error(`Package key already exists: ${input.key}`)
  }
  if (packages.some((item) => item.slug === input.slug)) {
    throw new Error(`Package slug already exists: ${input.slug}`)
  }

  mkdirSync(paths.landingDirectory, { recursive: true })
  mkdirSync(paths.offerDirectory, { recursive: true })
  const landingPath = path.join(paths.landingDirectory, `${input.landingVariant}.tsx`)
  const offerPath = path.join(paths.offerDirectory, `${input.offerVariant}.tsx`)
  const created = []

  if (!existsSync(landingPath)) {
    writeFileSync(landingPath, landingTemplate(input.landingVariant))
    created.push(path.relative(rootDir, landingPath))
  }
  if (!existsSync(offerPath)) {
    writeFileSync(offerPath, offerTemplate(input.offerVariant))
    created.push(path.relative(rootDir, offerPath))
  }

  packages.push({
    key: input.key,
    slug: input.slug,
    channel: input.channel,
    status: input.status,
    landingVariant: input.landingVariant,
    quizVariant: input.quizVariant,
    offerVariant: input.offerVariant,
  })
  writeFileSync(paths.packages, `${JSON.stringify(packages, null, 2)}\n`)
  writeFunnelRegistries(rootDir)
  checkFunnelFiles(rootDir)

  return {
    created,
    packageKey: input.key,
    slug: input.slug,
    quizVariant: input.quizVariant,
    quizKind: quizVariant.quizKind,
  }
}

export function main(argv = process.argv.slice(2), rootDir = defaultRoot) {
  if (argv.includes("--write")) {
    writeFunnelRegistries(rootDir)
    checkFunnelFiles(rootDir)
    console.log("Funnel registries regenerated.")
    return
  }
  if (argv.includes("--check")) {
    checkFunnelFiles(rootDir)
    console.log("Funnel package definitions and registries are in sync.")
    return
  }

  const input = parseFunnelArgs(argv)
  if (input.help) {
    console.log(usage())
    return
  }
  const result = createFunnelPackage(input, rootDir)
  console.log(`Created funnel package ${result.packageKey} at /lp/${result.slug}`)
  console.log(`Quiz variant: ${result.quizVariant} (quiz kind: ${result.quizKind})`)
  if (result.created.length > 0) console.log(`Created variants:\n- ${result.created.join("\n- ")}`)
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  try {
    main()
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)
    console.error(usage())
    process.exit(1)
  }
}
