import assert from "node:assert/strict"
import test from "node:test"

import {
  COMPARED_COLUMNS,
  TOLERATED_DIFFERENCES,
  detectHandEdits,
  oldWriterColumnsForArtifact,
  oldWriterColumnsForLead,
} from "../src/lib/user-facts/backfill/detect-hand-edits"
import {
  planUserFactsBackfill,
  type LegacyProfileColumns,
  type LoadedUserRow,
  type PlannedFactsWrite,
  type UserFactsBackfillPlan,
} from "../src/lib/user-facts/backfill/plan-row"
import { quizSupersedesFacts } from "../src/lib/user-facts/account-link"
import { deriveDiagnosticsColumns } from "../src/lib/user-facts/derive-legacy-columns"
import { mergeDiagnosticsPatch } from "../src/lib/user-facts/hand-edit"
import { projectLegacyLeadToFacts } from "../src/lib/user-facts/project-legacy-lead"
import { saveUserFacts as saveUserFactsRpc } from "../src/lib/user-facts/save"
import type { DiagnosticsV1, DomainProvenance, QuizContextV1 } from "../src/lib/user-facts/schema"
import { toStage1Source } from "../src/lib/user-facts/stage1-source"
import { adaptPersonalPlanAnswersForOffer } from "../src/lib/personal-plan-quiz/offer-adapter"
import { runUserFactsBackfill } from "../scripts/user-facts/backfill"
import {
  mobileFactsDatabase,
  pgliteRpcClient,
  readRow,
} from "./mobile-profile-facts-pglite.fixtures"
import {
  applyUserFactsLock,
  id,
  insertProfile,
  migratedPersonalPlanDatabase,
  type PersonalPlanTestDb,
} from "./personal-plan-pglite-migration.fixtures"

/**
 * Clean-switch task 7, part A: the backfill never undoes a hand edit made after the quiz it
 * projects (plan 2026-09-30 §3 "a hand edit that is newer than a quiz is kept"). Each fixture is
 * a production shape: the columns main's old writer left for the source, then what a user or a
 * migration changed afterwards.
 */

const NOW = "2026-09-30T12:00:00.000Z"

const V3_ENVELOPE = {
  kind: "personal_plan",
  version: 3,
  answers: {
    texture: "wavy",
    thickness: "fine",
    density: "medium",
    goals: ["moisture", "shine"],
    routineClarity: "clear",
    resultReliability: "mostly",
    adaptationConfidence: "yes",
    currentConcerns: ["dry_lengths", "low_shine", "tangling"],
    primaryConcern: "low_shine",
    concernRecurrence: { concernId: "dry_lengths", frequency: "often" },
    hairLength: "long",
    hairSurface: "slightly_uneven",
    elasticResponse: "stretches_stays",
    chemicalTreatments: ["colored"],
    scalpOiliness: "oily",
    scalpConcerns: ["oily_dandruff", "irritated"],
    previousAttempts: "some_steps_helped",
    blockers: ["consistency"],
    routineStyle: "simple_reliable",
    meaningfulMoment: "everyday",
  },
} as const

const LEAD_ANSWERS = {
  structure: "curly",
  thickness: "coarse",
  density: "high",
  hair_length: "medium",
  fingertest: "rau",
  pulltest: "snaps",
  scalp_type: "trocken",
  has_scalp_issue: true,
  scalp_condition: "trockene_schuppen",
  concerns: ["dry_lengths", "tangling"],
  primary_concern: "tangling",
  goals: ["moisture", "shape_definition"],
  treatment: ["natur"],
}

const EMPTY: LegacyProfileColumns = {
  hair_texture: null,
  thickness: null,
  density: null,
  hair_length: null,
  cuticle_condition: null,
  protein_moisture_balance: null,
  scalp_type: null,
  scalp_condition: null,
  chemical_treatment: null,
  concerns: null,
  goals: null,
  desired_volume: null,
  primary_concern: null,
  towel_material: null,
  towel_technique: null,
  drying_method: null,
  styling_tools: null,
  heat_styling: null,
  uses_heat_protection: null,
  night_protection: null,
  brush_type: null,
}

const ARTIFACT = {
  id: "artifact-1",
  leadId: "lead-pp-1",
  quizAnswers: V3_ENVELOPE,
  createdAt: "2026-08-01T09:00:00.000Z",
}
const LEAD = { id: "lead-1", quizAnswers: LEAD_ANSWERS, createdAt: "2026-07-01T09:00:00.000Z" }
/**
 * The columns as production stored them — hand-written, never generated by the code under test
 * (fix round 5). The paid row: main's paid link over the offer adapter (inferred goals
 * less_frizz + healthy_scalp, low_shine dropped, no legacy main problem).
 */
const PAID_COLUMNS: LegacyProfileColumns = {
  ...EMPTY,
  hair_texture: "wavy",
  thickness: "fine",
  density: "medium",
  hair_length: "long",
  cuticle_condition: "slightly_rough",
  protein_moisture_balance: "stretches_stays",
  chemical_treatment: ["colored"],
  scalp_type: "oily",
  scalp_condition: "irritated",
  concerns: ["dryness", "tangling"],
  primary_concern: null,
  goals: ["less_frizz", "moisture", "healthy_scalp", "shine"],
}
/** The legacy-lead row: main's legacy link (German answers projected, main problem, goals). */
const LEAD_COLUMNS: LegacyProfileColumns = {
  ...EMPTY,
  hair_texture: "curly",
  thickness: "coarse",
  density: "high",
  hair_length: "medium",
  cuticle_condition: "rough",
  protein_moisture_balance: "snaps",
  chemical_treatment: ["natural"],
  scalp_type: "dry",
  scalp_condition: "dry_flakes",
  concerns: ["dryness", "tangling"],
  primary_concern: "tangling",
  goals: ["moisture", "curl_definition"],
}

function row(overrides: Partial<LoadedUserRow>): LoadedUserRow {
  return {
    userId: "user-1",
    factsRevision: 0,
    factsProvenance: {},
    columns: EMPTY,
    storedDomains: { diagnostics: false, care_habits: false, quiz_context: false },
    storedDiagnostics: null,
    storedCareHabits: null,
    artifact: null,
    legacyLead: null,
    plan: null,
    needVersions: [],
    drafts: [],
    ...overrides,
  }
}

function plan(overrides: Partial<LoadedUserRow>): UserFactsBackfillPlan {
  return planUserFactsBackfill(row(overrides), { now: NOW, catchUp: false })
}

function diagnosticsWrite(planned: UserFactsBackfillPlan) {
  const write = planned.writes.find((entry) => entry.domain === "diagnostics")
  assert.ok(write, "a diagnostics write is planned")
  return write as Extract<PlannedFactsWrite, { domain: "diagnostics" }>
}

function documentOf(planned: UserFactsBackfillPlan): DiagnosticsV1 {
  return mergeDiagnosticsPatch(null, diagnosticsWrite(planned).patch)
}

/** The 13 diagnostics columns, canonical (order-free, `[]` = NULL) for comparison. */
function canonical(columns: Record<string, unknown>) {
  const out: Record<string, unknown> = {}
  for (const column of [...COMPARED_COLUMNS, "desired_volume"]) {
    const value = columns[column] ?? null
    out[column] = Array.isArray(value)
      ? value.length > 0
        ? [...value].sort()
        : null
      : value instanceof Date
        ? value.toISOString()
        : value
  }
  return out
}

// ---------------------------------------------------------------------------
// The old writers, recomputed
// ---------------------------------------------------------------------------

test("old writer (paid): main's link over the offer adapter — inferred goals, capped concerns, no legacy main problem", () => {
  assert.deepEqual(oldWriterColumnsForArtifact(ARTIFACT), {
    hair_texture: "wavy",
    thickness: "fine",
    density: "medium",
    hair_length: "long",
    cuticle_condition: "slightly_rough",
    protein_moisture_balance: "stretches_stays",
    chemical_treatment: ["colored"],
    scalp_type: "oily",
    scalp_condition: "irritated",
    // low_shine has no legacy concern; the adapter keeps the rest.
    concerns: ["dryness", "tangling"],
    primary_concern: null,
    // Picked: moisture, shine. Inferred by the adapter: less_frizz (tangling), healthy_scalp.
    goals: ["less_frizz", "moisture", "healthy_scalp", "shine"],
  })
})

test("old writer (paid): the artifact's STORED canonical_profile wins over recomputing it (the adapter changed over time)", () => {
  const stored = {
    modelVersion: "personal_plan_canonical_v1",
    structure: "wavy",
    thickness: "fine",
    density: "medium",
    hair_length: "long",
    fingertest: "leicht_uneben",
    pulltest: "stretches_stays",
    scalp_type: "fettig",
    has_scalp_issue: true,
    scalp_condition: "gereizt",
    concerns: ["dryness"],
    treatment: ["gefaerbt"],
    goals: ["moisture", "shine"],
  }
  const written = oldWriterColumnsForArtifact({ ...ARTIFACT, canonicalProfile: stored })
  assert.deepEqual(written?.goals, ["moisture", "shine"])
  assert.deepEqual(written?.concerns, ["dryness"])
})

test("old writer (lead): main's legacy link incl. the main problem and the projected goals", () => {
  assert.deepEqual(oldWriterColumnsForLead(LEAD_ANSWERS), {
    hair_texture: "curly",
    thickness: "coarse",
    density: "high",
    hair_length: "medium",
    cuticle_condition: "rough",
    protein_moisture_balance: "snaps",
    chemical_treatment: ["natural"],
    scalp_type: "dry",
    scalp_condition: "dry_flakes",
    concerns: ["dryness", "tangling"],
    primary_concern: "tangling",
    goals: ["moisture", "curl_definition"],
  })
  assert.equal(oldWriterColumnsForLead(null), null, "no record: main skipped the link")
})

// ---------------------------------------------------------------------------
// Fixtures of the brief
// ---------------------------------------------------------------------------

test("untouched paid row: the quiz's native values win; only the adapter-inferred goals disappear", () => {
  const planned = plan({ artifact: ARTIFACT, columns: PAID_COLUMNS })
  const write = diagnosticsWrite(planned)
  const document = documentOf(planned)

  assert.deepEqual(planned.report.editedGroups, [])
  assert.deepEqual(planned.report.ambiguousGroups, [])
  assert.deepEqual(planned.report.findings, [])
  assert.equal(write.provenance.editedAt, undefined)
  assert.equal(write.provenance.fields, undefined)
  // Quiz-only values survive: the picked goals only, low_shine, the main problem, recurrence,
  // both scalp concerns.
  assert.deepEqual(document.goals, ["moisture", "shine"])
  assert.deepEqual(document.currentConcerns, ["dry_lengths", "low_shine", "tangling"])
  assert.equal(document.primaryConcern, "low_shine")
  assert.deepEqual(document.concernRecurrence, { concernId: "dry_lengths", frequency: "often" })
  assert.deepEqual(document.scalpConcerns, ["oily_dandruff", "irritated"])
  assert.deepEqual(document.source.raw, V3_ENVELOPE, "source.raw stays the verbatim envelope")
  assert.deepEqual(planned.report.visibleChanges, [
    {
      domain: "diagnostics",
      column: "goals",
      before: "less_frizz,moisture,healthy_scalp,shine",
      after: "moisture,shine",
    },
  ])
})

test("paid row with edited goals: the edited goals win as user facts with editedAt; everything else is the quiz's", () => {
  const planned = plan({
    artifact: ARTIFACT,
    // The old Ziele editor wrote the goals and their derived volume direction.
    columns: { ...PAID_COLUMNS, goals: ["volume", "moisture"], desired_volume: "more" },
  })
  const write = diagnosticsWrite(planned)
  const document = documentOf(planned)

  assert.deepEqual(planned.report.editedGroups, ["goals"])
  assert.deepEqual(planned.report.findings, [
    {
      group: "goals",
      column: "goals",
      verdict: "edited",
      columnValue: "volume,moisture",
      oldWriterValue: "less_frizz,moisture,healthy_scalp,shine",
    },
  ])
  assert.deepEqual(document.goals, ["moisture", "volume_balance"])
  assert.equal(document.volumeDirection, "more")
  assert.deepEqual(write.provenance.fields, { goals: "user", volumeDirection: "user" })
  // A web edit is only known to be newer than the quiz it changed (fix round 5 ruling, I3).
  assert.equal(write.provenance.editedAt, "2026-08-01T09:00:00.001Z")
  assert.deepEqual(planned.report.editedAt, {
    at: "2026-08-01T09:00:00.001Z",
    basis: "after_quiz",
    candidates: { after_quiz: "2026-08-01T09:00:00.001Z" },
  })
  assert.deepEqual(document.currentConcerns, ["dry_lengths", "low_shine", "tangling"])
  assert.deepEqual(planned.report.visibleChanges, [], "the user sees exactly what she saw")
})

test("edited hair length only: that one field is the user's, every other field stays the lead's", () => {
  const planned = plan({ legacyLead: LEAD, columns: { ...LEAD_COLUMNS, hair_length: "long" } })
  const write = diagnosticsWrite(planned)
  const document = documentOf(planned)
  const lead = projectLegacyLeadToFacts({
    leadId: LEAD.id,
    quizAnswers: LEAD_ANSWERS as never,
    takenAt: LEAD.createdAt,
  }).diagnostics

  assert.deepEqual(planned.report.editedGroups, ["hair_length"])
  assert.deepEqual(write.provenance.fields, { hairLength: "user" })
  assert.deepEqual({ ...document, hairLength: lead.hairLength }, lead)
  assert.equal(document.hairLength, "long")
  assert.deepEqual(planned.report.visibleChanges, [])
})

test("edited concerns with a quiz-only concern in the source: the edit wins, low_shine (never shown by the old editor) stays, a stale recurrence goes", () => {
  const planned = plan({
    artifact: ARTIFACT,
    columns: { ...PAID_COLUMNS, concerns: ["frizz"] },
  })
  const write = diagnosticsWrite(planned)
  const document = documentOf(planned)

  assert.deepEqual(planned.report.editedGroups, ["concerns"])
  assert.deepEqual(document.currentConcerns, ["frizz_flyaways", "low_shine"])
  assert.equal(document.primaryConcern, "low_shine", "her pick is still one of her concerns")
  assert.equal(document.concernRecurrence, undefined, "dry_lengths is no longer selected")
  assert.deepEqual(planned.report.notes, ["kept quiz-only concerns beside the edit: low_shine"])
  assert.deepEqual(write.provenance.fields, { currentConcerns: "user" })
  assert.deepEqual(
    planned.report.visibleChanges.map((change) => change.column),
    ["goals"],
    "the concerns the user sees are unchanged; only the paid row's inferred goals go",
  )
})

/** `scanner_profile_edits.profile_snapshot` as the iOS edit left it: the whole row. */
const IOS_SNAPSHOT = { ...LEAD_COLUMNS, thickness: "fine", updated_at: "2026-09-20T08:00:00+00" }

test("iOS-edited row: editedAt is the iOS edit's publication time for a column its snapshot holds", () => {
  const planned = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, thickness: "fine" },
    lastProfileEditAt: "2026-09-20T08:00:00.000Z",
    lastProfileEditSnapshot: IOS_SNAPSHOT,
  })
  const write = diagnosticsWrite(planned)
  assert.deepEqual(planned.report.editedGroups, ["thickness"])
  assert.equal(write.provenance.editedAt, "2026-09-20T08:00:00.000Z")
  assert.deepEqual(planned.report.editedAt, {
    at: "2026-09-20T08:00:00.000Z",
    basis: "ios_profile_edit",
    candidates: {
      ios_profile_edit: "2026-09-20T08:00:00.000Z",
      after_quiz: "2026-07-01T09:00:00.001Z",
    },
  })

  // Per the existing precedence rule: a quiz taken after the edit replaces it, an older one not.
  const facts = {
    diagnostics: documentOf(planned),
    provenance: { diagnostics: write.provenance as DomainProvenance },
  }
  assert.equal(quizSupersedesFacts(facts, "2026-09-21T00:00:00.000Z"), true)
  assert.equal(quizSupersedesFacts(facts, "2026-09-19T00:00:00.000Z"), false)
})

test("legacy-lead row edited in the Haar-Check editor (it saves every field at once): the changed columns win, the unchanged ones keep the lead's values", () => {
  const planned = plan({
    legacyLead: LEAD,
    columns: {
      ...LEAD_COLUMNS,
      hair_texture: "wavy",
      scalp_type: "oily",
      scalp_condition: null,
      chemical_treatment: ["colored"],
    },
  })
  const document = documentOf(planned)

  assert.deepEqual(planned.report.editedGroups, ["structure", "treatment", "scalp_type"])
  assert.equal(document.texture, "wavy")
  assert.deepEqual(document.chemicalTreatments, ["colored"])
  assert.equal(document.scalpOiliness, "oily")
  assert.deepEqual(document.scalpConcerns, [], "„no scalp issue“ is an answer")
  assert.equal(document.thickness, "coarse")
  assert.deepEqual(document.goals, ["moisture", "shape_definition"])
  assert.deepEqual(planned.report.visibleChanges, [])
})

test("row normalised by a column migration: density 'medium' set by 20260429120000 is no edit and is kept, not defaulted", () => {
  // An older, incomplete legacy lead (no density, no treatment answer): main's link wrote no
  // density, and 20260429120000 later set 'medium' on every profile without one.
  const answers: Record<string, unknown> = { ...LEAD_ANSWERS }
  delete answers.density
  delete answers.treatment
  const written = oldWriterColumnsForLead(answers)
  assert.equal(written && "density" in written, false, "main's link wrote no density")
  const planned = plan({
    legacyLead: { ...LEAD, quizAnswers: answers },
    columns: { ...LEAD_COLUMNS, density: "medium", chemical_treatment: [] },
  })
  const write = diagnosticsWrite(planned)

  assert.deepEqual(planned.report.editedGroups, [])
  assert.deepEqual(planned.report.ambiguousGroups, [])
  assert.deepEqual(planned.report.tolerated, [
    { column: "density", id: "density_default_migration" },
  ])
  assert.equal(write.patch.density, "medium")
  assert.deepEqual(write.provenance.fields, { density: "unknown_historical" })
  assert.equal(write.provenance.editedAt, undefined)
})

test("multi-lead user: the lead TAKEN last wins; an older one is only a fallback", () => {
  const older = {
    id: "lead-old",
    quizAnswers: { ...LEAD_ANSWERS, goals: ["moisture"] },
    createdAt: "2026-05-01T00:00:00.000Z",
  }
  const newest = { ...LEAD, id: "lead-new", createdAt: "2026-08-15T00:00:00.000Z" }

  const planned = plan({ legacyLead: newest, olderLegacyLeads: [older], columns: LEAD_COLUMNS })
  assert.equal(diagnosticsWrite(planned).provenance.source.id, "lead-new")
  assert.deepEqual(planned.report.editedGroups, [])

  // The newest quiz is unusable -> the next one by quiz time, never a guess.
  const fallback = plan({
    legacyLead: { ...newest, quizAnswers: {} },
    olderLegacyLeads: [older],
    columns: { ...LEAD_COLUMNS, goals: ["moisture"] },
  })
  assert.equal(diagnosticsWrite(fallback).provenance.source.id, "lead-old")
  assert.deepEqual(fallback.report.editedGroups, [])
  assert.deepEqual(fallback.skips, [], "a source that fell through is a note, never a skip")
  assert.match(
    fallback.notes[0] ?? "",
    /lead lead-new could not be projected \(no_diagnostic_signal\)/,
  )
})

test("latest own quiz wins across kinds: a legacy lead taken after the attached artifact beats it, and the report says so", () => {
  const later = { ...LEAD, id: "lead-later", createdAt: "2026-09-01T00:00:00.000Z" }
  const planned = plan({ artifact: ARTIFACT, legacyLead: later, columns: LEAD_COLUMNS })
  const write = diagnosticsWrite(planned)
  assert.equal(write.provenance.source.kind, "legacy_lead")
  assert.equal(write.provenance.source.id, "lead-later")
  assert.equal(
    planned.report.sourceNote,
    "legacy lead lead-later (2026-09-01T00:00:00.000Z) was taken after artifact artifact-1 (2026-08-01T09:00:00.000Z): the lead wins",
  )
  assert.equal(
    planned.writes.some((entry) => entry.domain === "quiz_context"),
    false,
    "a legacy lead carries no quiz context",
  )

  // Without both quiz times the precedence stays artifact first.
  const unknownTime = plan({
    artifact: { ...ARTIFACT, createdAt: null },
    legacyLead: later,
    columns: PAID_COLUMNS,
  })
  assert.equal(diagnosticsWrite(unknownTime).provenance.source.kind, "personal_plan_artifact")
})

test("fix round 10 (owner ruling): goals equal an OLDER own quiz's are that quiz's last link — the newer quiz's goals replace them, no user provenance, a SOURCE NOTE naming both quizzes, the visible change listed", async () => {
  const older = {
    id: "lead-old",
    quizAnswers: { ...LEAD_ANSWERS, goals: ["shine"] },
    createdAt: "2026-05-01T00:00:00.000Z",
  }
  const columns = { ...LEAD_COLUMNS, goals: ["shine"] }
  const planned = plan({ legacyLead: LEAD, olderLegacyLeads: [older], columns })
  const write = diagnosticsWrite(planned)

  assert.deepEqual(planned.report.editedGroups, [])
  assert.deepEqual(planned.report.ambiguousGroups, [], "not a hand edit, not ambiguous")
  assert.deepEqual(
    planned.report.findings.map(({ column, verdict }) => ({ column, verdict })),
    [{ column: "goals", verdict: "last_link" }],
  )
  assert.deepEqual(documentOf(planned).goals, ["moisture", "shape_definition"], "the winner's")
  assert.equal(write.provenance.fields, undefined, "no `user` provenance")
  assert.equal(write.provenance.editedAt, undefined, "no editedAt")
  assert.equal(
    planned.report.lastLinkNote,
    "goals matched quiz legacy lead lead-old (2026-05-01T00:00:00.000Z), winner legacy lead lead-1 (2026-07-01T09:00:00.000Z) taken later: the winner's goals replace them; the visible change is listed",
  )
  const goalsChange = planned.report.visibleChanges.find((change) => change.column === "goals")
  assert.ok(goalsChange, "the goals change is a visible change")
  assert.equal(goalsChange.before, "shine")
  assert.deepEqual(goalsChange.after.split(",").sort(), ["curl_definition", "moisture"])
  assert.deepEqual(
    planned.report.visibleChanges.map((change) => change.column),
    ["goals"],
    "nothing else changes",
  )

  // The dry-run report: the SOURCE NOTE with the change beside it, counted in the summary and in
  // the change-pattern table.
  const user = "44444444-4444-4444-8444-444444444444"
  const tables: Record<string, Record<string, unknown>[]> = {
    hair_profiles: [{ user_id: user, facts_revision: 0, facts_provenance: {}, ...columns }],
    leads: [
      { id: older.id, user_id: user, created_at: older.createdAt, quiz_answers: older.quizAnswers },
      { id: LEAD.id, user_id: user, created_at: LEAD.createdAt, quiz_answers: LEAD_ANSWERS },
    ],
  }
  const lines: string[] = []
  const summary = await runUserFactsBackfill([], {
    supabase: tableClient(tables) as never,
    now: NOW,
    log: (line) => lines.push(line),
  })
  assert.equal(summary.ambiguousRows, 0, "no ambiguous row")
  assert.equal(summary.handEditedRows, 0, "no hand-edited row")
  const noteAt = lines.findIndex((line) =>
    line.includes(`${user} SOURCE NOTE: goals matched quiz legacy lead lead-old`),
  )
  assert.ok(noteAt > 0, "the SOURCE NOTE is printed")
  assert.equal(
    lines[noteAt + 1],
    `    diagnostics.goals: ${goalsChange.before} -> ${goalsChange.after}`,
    "the visible change is printed beside the note",
  )
  assert.ok(
    lines.includes(`  ${"rows an older quiz's link wrote (winner replaces)".padEnd(42)} 1`),
    "counted in the summary",
  )
  const patternsAt = lines.findIndex((line) => line.startsWith("CHANGE PATTERNS ("))
  const patternRows = lines
    .slice(
      patternsAt + 1,
      lines.findIndex((line, index) => index > patternsAt && line === ""),
    )
    .map((line) => line.trim().replace(/\s+(\d+)$/, " | $1"))
  assert.deepEqual(
    patternRows,
    ["diagnostics.goals: shine -> curl_definition,moisture | 1"],
    "counted in the change-pattern table",
  )
})

test("fix round 10: goals that match NEITHER the winner's old writer NOR any older own quiz are still a hand edit and win", () => {
  const older = {
    id: "lead-old",
    quizAnswers: { ...LEAD_ANSWERS, goals: ["shine"] },
    createdAt: "2026-05-01T00:00:00.000Z",
  }
  const planned = plan({
    legacyLead: LEAD,
    olderLegacyLeads: [older],
    columns: { ...LEAD_COLUMNS, goals: ["volume", "moisture"], desired_volume: "more" },
  })
  const write = diagnosticsWrite(planned)
  assert.deepEqual(planned.report.editedGroups, ["goals"])
  assert.deepEqual(planned.report.ambiguousGroups, [])
  assert.equal(planned.report.lastLinkNote, undefined, "no last link")
  assert.deepEqual(documentOf(planned).goals, ["moisture", "volume_balance"], "the column wins")
  assert.deepEqual(write.provenance.fields, { goals: "user", volumeDirection: "user" })
  assert.equal(write.provenance.editedAt, "2026-07-01T09:00:00.001Z")
})

test("ambiguous: a main problem no editor wrote — the column wins", () => {
  const planned = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, primary_concern: "dryness" },
  })
  assert.deepEqual(planned.report.ambiguousGroups, ["concerns"])
  assert.equal(documentOf(planned).primaryConcern, "dry_lengths")
  assert.deepEqual(diagnosticsWrite(planned).provenance.fields, { primaryConcern: "user" })
})

test("fix round 6 (I5): the backfill of a lead with an „Etwas anderes“ note carries the note; nothing else changes", () => {
  const withNote = { ...LEAD, quizAnswers: { ...LEAD_ANSWERS, concerns_other_text: " stumpf " } }
  const planned = plan({ legacyLead: withNote, columns: LEAD_COLUMNS })
  assert.equal(documentOf(planned).currentConcernsOtherText, "stumpf")
  assert.deepEqual(planned.report.editedGroups, [])
  assert.deepEqual(planned.report.findings, [])
  assert.deepEqual(planned.report.visibleChanges, [])
  assert.equal(diagnosticsWrite(planned).provenance.editedAt, undefined)
})

test("a row with no source at all is imported from its columns, with nothing to detect", () => {
  const planned = plan({ columns: { ...EMPTY, hair_texture: "straight", goals: ["shine"] } })
  const write = diagnosticsWrite(planned)
  assert.equal(write.provenance.source.kind, "legacy_columns")
  assert.equal(write.provenance.editedAt, undefined)
  assert.deepEqual(planned.report.findings, [])
  assert.deepEqual(planned.report.editedGroups, [])
})

test("care habits follow the owner's decisions, and every column the write changes — erasures included — is listed", () => {
  // „Nie" next to a selected tool (decision 1, Nick 2026-09-30): she uses no heat tools — the
  // tool list goes, the level stays „Nie", and the report names the dropped tool and the rule.
  const planned = plan({
    legacyLead: LEAD,
    columns: {
      ...LEAD_COLUMNS,
      heat_styling: "never",
      styling_tools: ["flat_iron"],
      uses_heat_protection: false,
    },
  })
  assert.deepEqual(
    planned.report.visibleChanges.filter((change) => change.domain === "care_habits"),
    [{ domain: "care_habits", column: "styling_tools", before: "flat_iron", after: "[]" }],
  )
  assert.deepEqual(planned.report.careRules, ["never_with_tools"])

  // Decision 3 (intended): a heat level with no heat source is dropped — listed as an erasure.
  const levelOnly = plan({
    legacyLead: LEAD,
    columns: {
      ...LEAD_COLUMNS,
      heat_styling: "daily",
      styling_tools: null,
      drying_method: null,
      uses_heat_protection: true,
    },
  })
  assert.deepEqual(
    levelOnly.report.visibleChanges.filter((change) => change.domain === "care_habits"),
    [
      { domain: "care_habits", column: "heat_styling", before: "daily", after: "NULL" },
      { domain: "care_habits", column: "uses_heat_protection", before: "true", after: "false" },
    ],
  )
  assert.deepEqual(levelOnly.report.careRules, [])

  // Decision 4 (intended): nothing representable at all (a towel technique without a
  // material): no document is written, and the row is named instead of silently skipped.
  const unrepresentable = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, towel_material: null, towel_technique: "gentle_press" },
  })
  assert.equal(
    unrepresentable.writes.some((write) => write.domain === "care_habits"),
    false,
  )
  assert.deepEqual(unrepresentable.skips, [
    "care_habits: the care columns carry values the conversion cannot represent (towel_technique=gentle_press); no document written — the next care write replaces them",
  ])
})

// ---------------------------------------------------------------------------
// The tolerated differences, one by one
// ---------------------------------------------------------------------------

test("tolerated: every entry of TOLERATED_DIFFERENCES has a test below", () => {
  assert.deepEqual(Object.keys(TOLERATED_DIFFERENCES).sort(), [
    "array_order",
    "density_default_migration",
    "desired_volume_derived",
    "empty_array_vs_null",
    "goals_never_written",
    "hair_length_recovery",
    "never_projected",
    "primary_concern_unwritten",
    "scalp_condition_none_migration",
  ])
})

test("tolerated array_order: the same set in another order is no edit", () => {
  const planned = plan({
    legacyLead: LEAD,
    columns: {
      ...LEAD_COLUMNS,
      goals: ["curl_definition", "moisture"],
      concerns: ["tangling", "dryness"],
    },
  })
  assert.deepEqual(planned.report.findings, [])
})

test("tolerated empty_array_vs_null: [] and NULL are the same answer", () => {
  const answers = { ...LEAD_ANSWERS, concerns: [], goals: [] }
  const written = oldWriterColumnsForLead(answers)
  assert.deepEqual(written?.concerns, [])
  const planned = plan({
    legacyLead: { ...LEAD, quizAnswers: answers },
    columns: { ...LEAD_COLUMNS, concerns: null, primary_concern: null, goals: [] },
  })
  assert.deepEqual(planned.report.findings, [])
})

test("tolerated hair_length_recovery: a hair length the quiz lacked (the purchase-time form) is kept, not an edit", () => {
  const answers: Record<string, unknown> = { ...LEAD_ANSWERS }
  delete answers.hair_length
  const planned = plan({
    legacyLead: { ...LEAD, quizAnswers: answers },
    columns: { ...LEAD_COLUMNS, hair_length: "short" },
  })
  assert.deepEqual(planned.report.tolerated, [
    { column: "hair_length", id: "hair_length_recovery" },
  ])
  assert.equal(diagnosticsWrite(planned).patch.hairLength, "short")
  assert.deepEqual(diagnosticsWrite(planned).provenance.fields, {
    hairLength: "unknown_historical",
  })
})

test("tolerated scalp_condition_none_migration: an old 'none' the migration turned into NULL is no edit", () => {
  const native = projectLegacyLeadToFacts({
    leadId: "l",
    quizAnswers: LEAD_ANSWERS as never,
  }).diagnostics
  const analysis = detectHandEdits({
    native,
    columns: { ...LEAD_COLUMNS, scalp_condition: null },
    oldWriter: { ...oldWriterColumnsForLead(LEAD_ANSWERS), scalp_condition: "none" },
  })
  assert.deepEqual(analysis.tolerated, [
    { column: "scalp_condition", id: "scalp_condition_none_migration" },
  ])
  assert.deepEqual(analysis.findings, [])
})

test("tolerated desired_volume_derived: the editors' derived desired_volume is never compared", () => {
  const planned = plan({ legacyLead: LEAD, columns: { ...LEAD_COLUMNS, desired_volume: "less" } })
  assert.deepEqual(planned.report.findings, [])
})

test("tolerated primary_concern_unwritten: a NULL main problem (column younger than the link, iOS writers) is no edit", () => {
  const planned = plan({ legacyLead: LEAD, columns: { ...LEAD_COLUMNS, primary_concern: null } })
  assert.deepEqual(planned.report.tolerated, [
    { column: "primary_concern", id: "primary_concern_unwritten" },
  ])
  assert.equal(documentOf(planned).primaryConcern, "tangling", "the quiz's pick stays")
})

test("tolerated never_projected: a row that never received its quiz is filled from it and every change is listed", () => {
  const planned = plan({ artifact: ARTIFACT, columns: EMPTY })
  assert.deepEqual(planned.report.findings, [])
  assert.equal(
    planned.report.tolerated.every((entry) => entry.id === "never_projected"),
    true,
  )
  assert.equal(diagnosticsWrite(planned).provenance.editedAt, undefined)
  assert.deepEqual(
    planned.report.visibleChanges.find((change) => change.column === "hair_texture"),
    { domain: "diagnostics", column: "hair_texture", before: "NULL", after: "wavy" },
  )
})

// ---------------------------------------------------------------------------
// Fix round 5 (review of task 7): I1 empty goals, I2 catch-up, I3 editedAt, I4 last link
// ---------------------------------------------------------------------------

/** An untouched paid row as main's plan-bereit link left it (`readiness.ts persistProfileOutput`
 * deletes `goals` from the upsert and never writes `primary_concern`): goals at the column
 * default `{}`, primary_concern NULL, every other column the paid projection. */
const READINESS_PAID_COLUMNS: LegacyProfileColumns = {
  ...EMPTY,
  hair_texture: "wavy",
  thickness: "fine",
  density: "medium",
  hair_length: "long",
  cuticle_condition: "slightly_rough",
  protein_moisture_balance: "stretches_stays",
  chemical_treatment: ["colored"],
  scalp_type: "oily",
  scalp_condition: "irritated",
  concerns: ["dryness", "tangling"],
  primary_concern: null,
  goals: [],
}

test("tolerated goals_never_written (I1): an untouched paid row from the readiness link — empty goals are filled by the source and listed, never an edit", () => {
  const planned = plan({ artifact: ARTIFACT, columns: READINESS_PAID_COLUMNS })
  const write = diagnosticsWrite(planned)

  assert.deepEqual(planned.report.editedGroups, [])
  assert.deepEqual(planned.report.ambiguousGroups, [])
  assert.deepEqual(planned.report.findings, [])
  assert.deepEqual(planned.report.tolerated, [{ column: "goals", id: "goals_never_written" }])
  assert.equal(write.provenance.editedAt, undefined)
  assert.equal(write.provenance.fields, undefined)
  assert.deepEqual(documentOf(planned).goals, ["moisture", "shine"], "the goals she picked")
  assert.deepEqual(planned.report.visibleChanges, [
    { domain: "diagnostics", column: "goals", before: "[]", after: "moisture,shine" },
  ])

  // The same for a legacy lead linked by the readiness path, and when the old writer cannot be
  // recomputed (the source's own derivation stands in for it).
  const lead = plan({ legacyLead: LEAD, columns: { ...LEAD_COLUMNS, goals: null } })
  assert.deepEqual(lead.report.findings, [])
  assert.deepEqual(documentOf(lead).goals, ["moisture", "shape_definition"])
  const analysis = detectHandEdits({
    native: projectLegacyLeadToFacts({ leadId: "l", quizAnswers: LEAD_ANSWERS as never })
      .diagnostics,
    columns: { ...LEAD_COLUMNS, goals: [] },
    oldWriter: null,
  })
  assert.deepEqual(analysis.findings, [])
  assert.deepEqual(analysis.tolerated, [{ column: "goals", id: "goals_never_written" }])
})

test("editedAt (I3): an iOS edit plus a later web edit in another group — the iOS time only dates the column its snapshot holds", () => {
  // iOS edit (thickness) on 2026-09-20; afterwards a web edit of the structure, which the
  // snapshot does not hold: newer than the iOS publication.
  const planned = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, thickness: "fine", hair_texture: "wavy" },
    lastProfileEditAt: "2026-09-20T08:00:00.000Z",
    lastProfileEditSnapshot: IOS_SNAPSHOT,
  })
  assert.deepEqual(planned.report.editedGroups, ["structure", "thickness"])
  assert.deepEqual(planned.report.editedAt, {
    at: "2026-09-20T08:00:00.000Z",
    basis: "ios_profile_edit",
    candidates: {
      ios_profile_edit: "2026-09-20T08:00:00.000Z",
      after_quiz: "2026-07-01T09:00:00.001Z",
    },
  })

  // An iOS publication OLDER than the winning quiz (a registration, then a later quiz): the
  // group its snapshot holds keeps the iOS time, the web edit is only known to be newer than
  // the quiz — the domain takes the later of the two.
  const registeredEarlier = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, thickness: "fine", hair_texture: "wavy" },
    lastProfileEditAt: "2026-06-01T08:00:00.000Z",
    lastProfileEditSnapshot: IOS_SNAPSHOT,
  })
  assert.deepEqual(registeredEarlier.report.editedAt, {
    at: "2026-07-01T09:00:00.001Z",
    basis: "after_quiz",
    candidates: {
      ios_profile_edit: "2026-06-01T08:00:00.000Z",
      after_quiz: "2026-07-01T09:00:00.001Z",
    },
  })
  // Only the snapshot's own column edited -> the iOS time, even before the quiz.
  const iosOnly = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, thickness: "fine" },
    lastProfileEditAt: "2026-06-01T08:00:00.000Z",
    lastProfileEditSnapshot: IOS_SNAPSHOT,
  })
  assert.equal(iosOnly.report.editedAt?.at, "2026-06-01T08:00:00.000Z")
})

test("editedAt (I3): an edit followed by a newer quiz linked after the backfill — the quiz wins (updated_at is never the edit time)", () => {
  // Paid quiz 2026-08-01, goals edited afterwards; hair_profiles.updated_at would say 2026-09-10.
  const planned = plan({
    artifact: ARTIFACT,
    columns: { ...PAID_COLUMNS, goals: ["volume", "moisture"], desired_volume: "more" },
  })
  const facts = {
    diagnostics: documentOf(planned),
    provenance: { diagnostics: diagnosticsWrite(planned).provenance as DomainProvenance },
  }
  // A newer quiz (taken 2026-08-15, before that updated_at), linked only after the backfill.
  assert.equal(quizSupersedesFacts(facts, "2026-08-15T00:00:00.000Z"), true)
  // An older quiz still never overwrites.
  assert.equal(quizSupersedesFacts(facts, "2026-07-15T00:00:00.000Z"), false)
})

test("editedAt (I3): a quiz taken before a chat-memory bump but after the edited state was reached wins", () => {
  // Lead quiz 2026-07-01, hair length edited on the web some time after. A quiz taken on
  // 2026-09-05; the chat's conversation_memory bumped updated_at on 2026-09-10.
  const planned = plan({ legacyLead: LEAD, columns: { ...LEAD_COLUMNS, hair_length: "long" } })
  const write = diagnosticsWrite(planned)
  assert.equal(write.provenance.editedAt, "2026-07-01T09:00:00.001Z")
  const facts = {
    diagnostics: documentOf(planned),
    provenance: { diagnostics: write.provenance as DomainProvenance },
  }
  assert.equal(quizSupersedesFacts(facts, "2026-09-05T00:00:00.000Z"), true)
})

/** A read-only PostgREST-shaped client over in-memory tables (no filtering: one user). */
function tableClient(tables: Record<string, Record<string, unknown>[]>) {
  return {
    from(table: string) {
      const builder = {
        select: () => builder,
        eq: () => builder,
        in: () => builder,
        gt: () => builder,
        order: () => builder,
        limit: () => builder,
        then: (resolve: (result: { data: unknown[]; error: null }) => unknown) =>
          resolve({ data: tables[table] ?? [], error: null }),
      }
      return builder
    },
    rpc: async () => {
      throw new Error("a dry run never writes")
    },
  }
}

test("last link (fix round 6, I4): columns an OLDER quiz's link wrote — the winner's answers replace them, a SOURCE NOTE, every visible change listed", async () => {
  // The artifact (taken 2026-08-01) wins by quiz time; the older lead (2026-07-01) was linked by
  // email fallback AFTER the paid link, so the row is exactly what the lead's link wrote. §3: the
  // quiz taken later fully replaces — the older quiz's answers never survive in its document.
  const planned = plan({ artifact: ARTIFACT, legacyLead: LEAD, columns: LEAD_COLUMNS })
  const write = diagnosticsWrite(planned)
  const document = documentOf(planned)

  assert.equal(write.provenance.source.kind, "personal_plan_artifact")
  assert.equal(
    planned.report.lastLinkNote,
    "columns matched quiz legacy lead lead-1 (2026-07-01T09:00:00.000Z), winner artifact artifact-1 (2026-08-01T09:00:00.000Z) taken later: the winner's answers replace the columns; every visible change is listed",
  )
  assert.deepEqual(planned.report.editedGroups, [])
  // The winner's stated answers, not the older quiz's columns.
  assert.equal(document.texture, "wavy")
  assert.equal(document.thickness, "fine")
  assert.equal(document.hairLength, "long")
  assert.equal(document.primaryConcern, "low_shine")
  assert.deepEqual(document.scalpConcerns, ["oily_dandruff", "irritated"])
  assert.ok(
    planned.report.findings.every((finding) => finding.verdict === "last_link"),
    "every differing column, the goals included, is the older quiz's link (fix round 10)",
  )
  // Every resulting visible change is listed for the owner.
  const after = deriveDiagnosticsColumns(document) as unknown as Record<string, unknown>
  const changed = [...DIAGNOSTIC_COLUMN_NAMES].filter(
    (column) =>
      JSON.stringify(canonical(after)[column]) !==
      JSON.stringify(canonical(LEAD_COLUMNS as unknown as Record<string, unknown>)[column]),
  )
  assert.ok(
    changed.includes("hair_texture") && changed.includes("thickness") && changed.includes("goals"),
    "texture, thickness and goals change visibly",
  )
  assert.deepEqual(
    planned.report.visibleChanges.map((change) => change.column).sort(),
    [...changed].sort(),
  )
  // Fix round 10 (owner ruling): goals equal to the OLDER quiz's are its link too — the winner's
  // goals replace them; nothing is a hand edit, so no `user` field and no editedAt.
  assert.deepEqual(planned.report.ambiguousGroups, [])
  assert.deepEqual(document.goals, ["moisture", "shine"], "the winner's picked goals")
  assert.equal(write.provenance.fields, undefined)
  assert.equal(write.provenance.editedAt, undefined)

  // The dry-run report prints the SOURCE NOTE and every visible change beside it.
  const user = "33333333-3333-4333-8333-333333333333"
  const tables: Record<string, Record<string, unknown>[]> = {
    hair_profiles: [
      { user_id: user, facts_revision: 0, facts_provenance: {}, ...EMPTY, ...LEAD_COLUMNS },
    ],
    personal_plan_prepared_artifacts: [
      {
        id: ARTIFACT.id,
        lead_id: ARTIFACT.leadId,
        user_id: user,
        created_at: ARTIFACT.createdAt,
        quiz_answers: V3_ENVELOPE,
        canonical_profile: adaptedCanonical(),
      },
    ],
    leads: [{ id: LEAD.id, user_id: user, created_at: LEAD.createdAt, quiz_answers: LEAD_ANSWERS }],
  }
  const lines: string[] = []
  await runUserFactsBackfill([], {
    supabase: tableClient(tables) as never,
    now: NOW,
    log: (line) => lines.push(line),
  })
  const noteAt = lines.findIndex((line) => line.includes("SOURCE NOTE: columns matched quiz"))
  assert.ok(noteAt > 0)
  const printed = lines.slice(noteAt + 1).filter((line) => line.startsWith("    diagnostics."))
  for (const change of planned.report.visibleChanges) {
    assert.ok(
      printed.includes(`    diagnostics.${change.column}: ${change.before} -> ${change.after}`),
      change.column,
    )
  }
  assert.ok(lines.includes(`  ${"rows an older quiz's link wrote (winner replaces)".padEnd(42)} 1`))

  // A hand edit on top of that link is no longer "the link": an ordinary edit.
  const editedAfter = plan({
    artifact: ARTIFACT,
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, hair_length: "short" },
  })
  assert.ok(editedAfter.report.editedGroups.includes("hair_length"), "hair length is an edit")
  // ... while its goals are still the older quiz's: only they get the note (fix round 10).
  assert.equal(
    editedAfter.report.lastLinkNote,
    "goals matched quiz legacy lead lead-1 (2026-07-01T09:00:00.000Z), winner artifact artifact-1 (2026-08-01T09:00:00.000Z) taken later: the winner's goals replace them; the visible change is listed",
  )
  assert.deepEqual(documentOf(editedAfter).goals, ["moisture", "shine"], "the winner's goals")
})

test("--catch-up (I2): applied untouched paid row + one live thickness write -> only thickness is an edit; goals keep the document's native values", () => {
  const first = plan({ artifact: ARTIFACT, columns: PAID_COLUMNS })
  const stored = documentOf(first)
  const storedProvenance = diagnosticsWrite(first).provenance as DomainProvenance
  const applied = deriveDiagnosticsColumns(stored)
  const catchUp = planUserFactsBackfill(
    row({
      factsRevision: 2,
      factsProvenance: { diagnostics: storedProvenance },
      storedDomains: { diagnostics: true, care_habits: false, quiz_context: true },
      storedDiagnostics: stored,
      artifact: ARTIFACT,
      // What the door derived at --apply, then one legacy write before the deploy.
      columns: { ...EMPTY, ...applied, thickness: "coarse" } as LegacyProfileColumns,
    }),
    { now: "2026-10-02T12:00:00.000Z", catchUp: true },
  )
  const write = diagnosticsWrite(catchUp)
  const document = mergeDiagnosticsPatch(stored, write.patch)

  assert.deepEqual(catchUp.report.editedGroups, ["thickness"])
  assert.deepEqual(catchUp.report.ambiguousGroups, [])
  assert.deepEqual(write.provenance.fields, { thickness: "user" })
  assert.equal(document.thickness, "coarse")
  assert.deepEqual(document.goals, ["moisture", "shine"], "not re-converted from the columns")
  assert.equal(document.primaryConcern, "low_shine")
  assert.deepEqual(document.concernRecurrence, stored.concernRecurrence)
  assert.deepEqual(write.provenance.source, storedProvenance.source)
  // Changed since the backfill wrote the document: newer than its `at`.
  assert.deepEqual(catchUp.report.editedAt, {
    at: NOW,
    basis: "after_backfill",
    candidates: { after_quiz: "2026-08-01T09:00:00.001Z", after_backfill: NOW },
  })
  assert.deepEqual(catchUp.report.visibleChanges, [])
})

test("--catch-up (I2): existing user fields and editedAt carry over; only the column changed since is added", () => {
  const first = plan({
    legacyLead: LEAD,
    columns: { ...LEAD_COLUMNS, hair_texture: "wavy" },
    lastProfileEditAt: "2026-10-05T08:00:00.000Z",
    lastProfileEditSnapshot: { ...LEAD_COLUMNS, hair_texture: "wavy" },
  })
  const stored = documentOf(first)
  const storedProvenance = diagnosticsWrite(first).provenance as DomainProvenance
  assert.equal(storedProvenance.editedAt, "2026-10-05T08:00:00.000Z")
  const catchUp = planUserFactsBackfill(
    row({
      factsRevision: 1,
      factsProvenance: { diagnostics: storedProvenance },
      storedDomains: { diagnostics: true, care_habits: false, quiz_context: false },
      storedDiagnostics: stored,
      legacyLead: LEAD,
      columns: {
        ...EMPTY,
        ...deriveDiagnosticsColumns(stored),
        hair_length: "short",
      } as LegacyProfileColumns,
    }),
    { now: "2026-10-06T12:00:00.000Z", catchUp: true },
  )
  const write = diagnosticsWrite(catchUp)
  assert.deepEqual(catchUp.report.editedGroups, ["hair_length"])
  assert.deepEqual(write.provenance.fields, { texture: "user", hairLength: "user" })
  // The stored editedAt (later than the backfill's own write here) is never lowered.
  assert.equal(write.provenance.editedAt, "2026-10-05T08:00:00.000Z")
  assert.equal(catchUp.report.editedAt?.basis, "stored_edited_at")
  assert.equal(mergeDiagnosticsPatch(stored, write.patch).texture, "wavy")
})

// ---------------------------------------------------------------------------
// Fix round 6 (I3): --catch-up when the winning quiz changed brings quiz_context along
// ---------------------------------------------------------------------------

/** A row the backfill wrote from ARTIFACT (diagnostics + quiz_context), as `--catch-up` loads it. */
function backfilledFromArtifact(overrides: Partial<LoadedUserRow>): LoadedUserRow {
  const first = plan({ artifact: ARTIFACT, columns: PAID_COLUMNS })
  const diagnostics = documentOf(first)
  const context = first.writes.find((write) => write.domain === "quiz_context")!
  return row({
    factsRevision: 2,
    factsProvenance: {
      diagnostics: diagnosticsWrite(first).provenance as DomainProvenance,
      quiz_context: context.provenance as DomainProvenance,
    },
    storedDomains: { diagnostics: true, care_habits: false, quiz_context: true },
    storedDiagnostics: diagnostics,
    storedQuizContext: context.patch as QuizContextV1,
    artifact: ARTIFACT,
    columns: { ...EMPTY, ...deriveDiagnosticsColumns(diagnostics) } as LegacyProfileColumns,
    ...overrides,
  })
}

const LEAD_B = { ...LEAD, id: "lead-b", createdAt: "2026-09-10T09:00:00.000Z" }

test("I3: --catch-up — a newer legacy lead linked through the legacy columns wins, and the artifact's quiz_context is cleared", () => {
  // Main's legacy link of lead B wrote LEAD_COLUMNS directly between --apply and the catch-up.
  const planned = planUserFactsBackfill(
    backfilledFromArtifact({ legacyLead: LEAD_B, columns: LEAD_COLUMNS }),
    { now: "2026-10-02T12:00:00.000Z", catchUp: true },
  )
  const write = diagnosticsWrite(planned)
  assert.deepEqual(write.provenance.source, { kind: "legacy_lead", id: "lead-b" })
  const context = planned.writes.find((entry) => entry.domain === "quiz_context")
  assert.ok(context, "the context domain is planned alongside diagnostics")
  assert.equal(
    Object.values(context.patch).every((value) => value === null),
    true,
    "a legacy lead carries no context: every field cleared",
  )
  assert.ok(Object.keys(context.patch).includes("routineClarity"))
  assert.deepEqual(context.provenance.source, { kind: "legacy_lead", id: "lead-b" })
  assert.ok(
    planned.notes.some((note) =>
      note.startsWith(
        "quiz_context: catch-up — legacy lead lead-b (2026-09-10T09:00:00.000Z) now wins",
      ),
    ),
    planned.notes.join("\n"),
  )
})

test("I3: --catch-up — a newer artifact replaces the stored quiz_context with its own", () => {
  const envelope = {
    ...V3_ENVELOPE,
    answers: { ...V3_ENVELOPE.answers, thickness: "coarse", routineStyle: "flexible_versatile" },
  }
  const newer = {
    id: "artifact-2",
    leadId: "lead-pp-2",
    quizAnswers: envelope,
    createdAt: "2026-09-10T09:00:00.000Z",
  }
  const planned = planUserFactsBackfill(
    backfilledFromArtifact({
      artifact: newer,
      columns: {
        ...EMPTY,
        ...(oldWriterColumnsForArtifact(newer) as Partial<LegacyProfileColumns>),
      },
    }),
    { now: "2026-10-02T12:00:00.000Z", catchUp: true },
  )
  assert.deepEqual(diagnosticsWrite(planned).provenance.source, {
    kind: "personal_plan_artifact",
    id: "artifact-2",
  })
  const context = planned.writes.find((entry) => entry.domain === "quiz_context")
  assert.ok(context, "the context domain is planned alongside diagnostics")
  assert.equal((context.patch as QuizContextV1).routineStyle, "flexible_versatile")
  assert.deepEqual(context.provenance.source, { kind: "personal_plan_artifact", id: "artifact-2" })
  assert.equal(
    planned.skips.some((skip) => skip.startsWith("quiz_context")),
    false,
    planned.skips.join("\n"),
  )
})

test("I3: --catch-up with an unchanged winner writes no quiz_context", () => {
  const stored = backfilledFromArtifact({})
  const planned = planUserFactsBackfill(
    { ...stored, columns: { ...stored.columns, thickness: "coarse" } },
    { now: "2026-10-02T12:00:00.000Z", catchUp: true },
  )
  assert.ok(diagnosticsWrite(planned), "diagnostics is re-planned")
  assert.equal(
    planned.writes.some((entry) => entry.domain === "quiz_context"),
    false,
  )
})

// ---------------------------------------------------------------------------
// Fix round 7 (A, B): the context domain is decided on its own consistency with diagnostics
// ---------------------------------------------------------------------------

const CATCH_UP_NOW = "2026-10-02T12:00:00.000Z"
const RERUN_NOW = "2026-10-03T12:00:00.000Z"

/** The state a failed catch-up leaves: lead B's diagnostics landed, replacing artifact A's
 * context failed — A's context (with answers) stays next to B's diagnostics. */
function halfPublishedLeadB(overrides: Partial<LoadedUserRow> = {}): LoadedUserRow {
  const base = backfilledFromArtifact({ legacyLead: LEAD_B, columns: LEAD_COLUMNS })
  const catchUp = planUserFactsBackfill(base, { now: CATCH_UP_NOW, catchUp: true })
  const diagnostics = documentOf(catchUp)
  return {
    ...base,
    factsRevision: 3,
    factsProvenance: {
      ...base.factsProvenance,
      diagnostics: diagnosticsWrite(catchUp).provenance as DomainProvenance,
    },
    storedDiagnostics: diagnostics,
    columns: { ...EMPTY, ...deriveDiagnosticsColumns(diagnostics) } as LegacyProfileColumns,
    ...overrides,
  }
}

function contextWrites(planned: UserFactsBackfillPlan) {
  return planned.writes.filter(
    (entry): entry is Extract<PlannedFactsWrite, { domain: "quiz_context" }> =>
      entry.domain === "quiz_context",
  )
}

for (const catchUp of [false, true]) {
  const mode = catchUp ? "--catch-up" : "plain re-run"
  test(`fix round 7 (A, ${mode}): B's diagnostics next to A's context — the context is cleared to B's target, diagnostics untouched`, () => {
    const stored = halfPublishedLeadB()
    assert.ok(
      Object.keys(stored.storedQuizContext ?? {}).length > 0,
      "precondition: A's context holds answers",
    )
    const planned = planUserFactsBackfill(stored, { now: RERUN_NOW, catchUp })
    assert.deepEqual(
      planned.writes.map((entry) => entry.domain),
      ["quiz_context"],
      `one context write, no diagnostics write\n${planned.skips.join("\n")}`,
    )
    const [context] = contextWrites(planned)
    assert.equal(
      Object.values(context!.patch).every((value) => value === null),
      true,
      "a legacy lead carries no context: every field cleared",
    )
    assert.deepEqual(context!.provenance.source, { kind: "legacy_lead", id: "lead-b" })
    assert.ok(
      planned.notes.some((note) =>
        note.startsWith(
          "quiz_context: the stored context comes from artifact artifact-1, the stored diagnostics from legacy lead lead-b",
        ),
      ),
      planned.notes.join("\n"),
    )
  })

  test(`fix round 7 (A, ${mode}): a consistent pair plans nothing (idempotent after the repair)`, () => {
    const repaired = halfPublishedLeadB({
      factsRevision: 4,
      storedQuizContext: {},
      factsProvenance: {
        ...halfPublishedLeadB().factsProvenance,
        quiz_context: {
          source: { kind: "legacy_lead", id: "lead-b" },
          schemaVersion: 1,
          at: RERUN_NOW,
        },
      },
    })
    const planned = planUserFactsBackfill(repaired, { now: "2026-10-04T12:00:00.000Z", catchUp })
    assert.deepEqual(planned.writes, [], planned.skips.join("\n"))

    const untouched = planUserFactsBackfill(backfilledFromArtifact({}), {
      now: RERUN_NOW,
      catchUp,
    })
    assert.equal(contextWrites(untouched).length, 0, "artifact A + its own context: consistent")
  })

  test(`fix round 7 (A, ${mode}): diagnostics from a newer ARTIFACT next to A's context — the context becomes that artifact's own`, () => {
    const envelope = {
      ...V3_ENVELOPE,
      answers: { ...V3_ENVELOPE.answers, thickness: "coarse", routineStyle: "flexible_versatile" },
    }
    const newer = {
      id: "artifact-2",
      leadId: "lead-pp-2",
      quizAnswers: envelope,
      createdAt: "2026-09-10T09:00:00.000Z",
    }
    const base = backfilledFromArtifact({
      artifact: newer,
      columns: {
        ...EMPTY,
        ...(oldWriterColumnsForArtifact(newer) as Partial<LegacyProfileColumns>),
      },
    })
    const catchUpPlan = planUserFactsBackfill(base, { now: CATCH_UP_NOW, catchUp: true })
    const diagnostics = documentOf(catchUpPlan)
    const stored: LoadedUserRow = {
      ...base,
      factsRevision: 3,
      factsProvenance: {
        ...base.factsProvenance,
        diagnostics: diagnosticsWrite(catchUpPlan).provenance as DomainProvenance,
      },
      storedDiagnostics: diagnostics,
      columns: { ...EMPTY, ...deriveDiagnosticsColumns(diagnostics) } as LegacyProfileColumns,
    }
    const planned = planUserFactsBackfill(stored, { now: RERUN_NOW, catchUp })
    assert.deepEqual(
      planned.writes.map((entry) => entry.domain),
      ["quiz_context"],
      planned.skips.join("\n"),
    )
    const [context] = contextWrites(planned)
    assert.equal((context!.patch as QuizContextV1).routineStyle, "flexible_versatile")
    assert.deepEqual(context!.provenance.source, {
      kind: "personal_plan_artifact",
      id: "artifact-2",
    })
  })

  test(`fix round 7 (A, ${mode}): diagnostics from an artifact that is not the attached one — its context cannot be read, left for review`, () => {
    const stored = halfPublishedLeadB()
    const foreign = backfilledFromArtifact({}).storedDiagnostics!
    const planned = planUserFactsBackfill(
      {
        ...stored,
        storedDiagnostics: {
          ...foreign,
          source: {
            ...foreign.source,
            artifactId: "artifact-elsewhere",
          } as DiagnosticsV1["source"],
        },
        columns: { ...EMPTY, ...deriveDiagnosticsColumns(foreign) } as LegacyProfileColumns,
      },
      { now: RERUN_NOW, catchUp },
    )
    assert.equal(contextWrites(planned).length, 0, planned.notes.join("\n"))
    assert.ok(
      planned.skips.some(
        (skip) =>
          skip.startsWith("quiz_context: the stored context comes from artifact artifact-1") &&
          skip.includes("left for review"),
      ),
      planned.skips.join("\n"),
    )
  })

  // B: the ownership rule. A context the account link or the backfill wrote follows the
  // latest-quiz rule; a context any user-edit (or unknown) writer wrote is never touched.
  for (const kind of [
    "feinschliff_draft",
    "onboarding",
    "profile_editor",
    "account_link",
  ] as const) {
    test(`fix round 7 (B, ${mode}): a ${kind} context next to inconsistent diagnostics is never touched`, () => {
      const stored = halfPublishedLeadB()
      const planned = planUserFactsBackfill(
        {
          ...stored,
          factsProvenance: {
            ...stored.factsProvenance,
            quiz_context: { source: { kind }, schemaVersion: 1, at: "2026-09-20T09:00:00.000Z" },
          },
        },
        { now: RERUN_NOW, catchUp },
      )
      assert.equal(contextWrites(planned).length, 0, planned.notes.join("\n"))
      assert.equal(planned.writes.length, 0, "nothing else is planned either")
    })
  }
}

for (const kind of ["feinschliff_draft", "onboarding", "profile_editor", "account_link"] as const) {
  test(`fix round 7 (B): --catch-up with a changed winner never replaces a ${kind} context`, () => {
    const stored = backfilledFromArtifact({ legacyLead: LEAD_B, columns: LEAD_COLUMNS })
    const planned = planUserFactsBackfill(
      {
        ...stored,
        factsProvenance: {
          ...stored.factsProvenance,
          quiz_context: { source: { kind }, schemaVersion: 1, at: "2026-09-20T09:00:00.000Z" },
        },
      },
      { now: CATCH_UP_NOW, catchUp: true },
    )
    assert.ok(diagnosticsWrite(planned), "diagnostics still follow the new winner")
    assert.equal(contextWrites(planned).length, 0, planned.notes.join("\n"))
    assert.ok(
      planned.skips.some(
        (skip) => skip.includes(`last written by ${kind}`) && skip.includes("never overwritten"),
      ),
      planned.skips.join("\n"),
    )
  })
}

test("fix round 7 (B): --catch-up with a changed winner never replaces a stored context that carries no provenance", () => {
  const stored = backfilledFromArtifact({ legacyLead: LEAD_B, columns: LEAD_COLUMNS })
  const { quiz_context: _dropped, ...provenance } = stored.factsProvenance
  const planned = planUserFactsBackfill(
    { ...stored, factsProvenance: provenance },
    { now: CATCH_UP_NOW, catchUp: true },
  )
  assert.equal(contextWrites(planned).length, 0, planned.notes.join("\n"))
  assert.ok(
    planned.skips.some((skip) => skip.includes("no quiz_context provenance")),
    planned.skips.join("\n"),
  )
})

for (const kind of ["personal_plan_artifact", "legacy_lead"] as const) {
  test(`fix round 7 (B): a ${kind} context (account link / backfill) follows the latest quiz — repaired when it names another quiz`, () => {
    const stored = halfPublishedLeadB()
    const planned = planUserFactsBackfill(
      {
        ...stored,
        factsProvenance: {
          ...stored.factsProvenance,
          quiz_context: {
            source: { kind, id: "some-earlier-quiz" },
            schemaVersion: 1,
            at: "2026-09-20T09:00:00.000Z",
          },
        },
      },
      { now: RERUN_NOW, catchUp: false },
    )
    assert.equal(contextWrites(planned).length, 1, planned.skips.join("\n"))
  })
}

// ---------------------------------------------------------------------------
// Stage 1 for a hand-edited backfilled row
// ---------------------------------------------------------------------------

test("Stage 1: an untouched backfilled row re-emits its verbatim envelope; a hand-edited one emits a native envelope built from the edited facts", () => {
  const quizContext = planUserFactsBackfill(row({ artifact: ARTIFACT, columns: PAID_COLUMNS }), {
    now: NOW,
    catchUp: false,
  }).writes.find((write) => write.domain === "quiz_context")?.patch as QuizContextV1

  const untouched = plan({ artifact: ARTIFACT, columns: PAID_COLUMNS })
  assert.deepEqual(
    toStage1Source({
      diagnostics: documentOf(untouched),
      quizContext,
      editedAt: diagnosticsWrite(untouched).provenance.editedAt,
      fields: diagnosticsWrite(untouched).provenance.fields,
    }),
    V3_ENVELOPE,
  )

  const edited = plan({
    artifact: ARTIFACT,
    columns: { ...PAID_COLUMNS, goals: ["volume", "moisture"], desired_volume: "more" },
  })
  const document = documentOf(edited)
  assert.deepEqual(document.source.raw, V3_ENVELOPE, "raw stays the verbatim quiz envelope")
  const emitted = toStage1Source({
    diagnostics: document,
    quizContext,
    editedAt: diagnosticsWrite(edited).provenance.editedAt,
    fields: diagnosticsWrite(edited).provenance.fields,
  }) as { kind: string; version: number; answers: Record<string, unknown> }
  assert.equal(emitted.kind, "personal_plan")
  assert.equal(emitted.version, 3)
  assert.deepEqual(emitted.answers.goals, ["moisture", "volume_balance"])
  assert.equal(emitted.answers.primaryConcern, "low_shine")

  const editedLead = plan({ legacyLead: LEAD, columns: { ...LEAD_COLUMNS, hair_length: "long" } })
  const legacy = toStage1Source({
    diagnostics: documentOf(editedLead),
    editedAt: diagnosticsWrite(editedLead).provenance.editedAt,
    fields: diagnosticsWrite(editedLead).provenance.fields,
  }) as { kind: string; answers: { hairLength: string } }
  assert.equal(legacy.kind, "legacy_quiz")
  assert.equal(legacy.answers.hairLength, "long")
})

// ---------------------------------------------------------------------------
// Through the real door (PGlite, lock applied after the legacy seed — the rollout order)
// ---------------------------------------------------------------------------

const DIAGNOSTIC_COLUMN_NAMES = [...COMPARED_COLUMNS, "desired_volume"] as const

async function seedLegacyRow(
  pg: PersonalPlanTestDb,
  userId: string,
  columns: LegacyProfileColumns,
) {
  const values = Object.fromEntries(
    DIAGNOSTIC_COLUMN_NAMES.map((column) => [column, columns[column] ?? null]),
  )
  // A NULL for a `'{}'`-default array column is written as the default, like production rows.
  for (const column of ["chemical_treatment", "concerns", "goals"]) values[column] ??= []
  const names = Object.keys(values)
  await pg.query(
    `INSERT INTO public.hair_profiles (user_id, ${names.join(", ")})
     VALUES ($1, ${names.map((_, index) => `$${index + 2}`).join(", ")})`,
    [userId, ...Object.values(values)],
  )
}

async function applyPlanThroughDoor(
  pg: PersonalPlanTestDb,
  userId: string,
  planned: UserFactsBackfillPlan,
) {
  let expectedRevision = 0
  for (const write of planned.writes) {
    const result = await saveUserFactsRpc(
      pgliteRpcClient(pg) as never,
      {
        userId,
        domain: write.domain,
        patch: write.patch,
        provenance: write.provenance,
        expectedRevision,
        mode: "upsert",
      } as Parameters<typeof saveUserFactsRpc>[1],
    )
    assert.equal(result.status, "ok", write.domain)
    expectedRevision = (result as { revision: number }).revision
  }
  return (await readRow(pg, userId))!
}

for (const [label, overrides] of [
  [
    "paid row with edited goals",
    {
      artifact: ARTIFACT,
      columns: { ...PAID_COLUMNS, goals: ["volume", "moisture"], desired_volume: "more" },
    },
  ],
  [
    "lead row edited in the Haar-Check editor",
    {
      legacyLead: LEAD,
      columns: {
        ...LEAD_COLUMNS,
        hair_texture: "wavy",
        scalp_type: "oily",
        scalp_condition: null,
        chemical_treatment: ["colored"],
      },
    },
  ],
  [
    "paid row with edited concerns",
    { artifact: ARTIFACT, columns: { ...PAID_COLUMNS, concerns: ["frizz"] } },
  ],
  ["iOS-edited lead row", { legacyLead: LEAD, columns: { ...LEAD_COLUMNS, thickness: "fine" } }],
] as const) {
  test(`through the door under the lock (${label}): the derived columns equal the TS oracle and the pre-backfill columns`, async (t) => {
    const pg = await migratedPersonalPlanDatabase(t, { lock: false })
    const userId = id(7, 1)
    await insertProfile(pg, userId)
    const before = overrides.columns as LegacyProfileColumns
    await seedLegacyRow(pg, userId, before)
    await applyUserFactsLock(pg)

    const planned = plan({ ...(overrides as Partial<LoadedUserRow>), userId })
    const after = await applyPlanThroughDoor(pg, userId, planned)
    const oracle = deriveDiagnosticsColumns(documentOf(planned))

    assert.deepEqual(canonical(after), canonical(oracle), "SQL door = TS oracle")
    const intended = new Set(planned.report.visibleChanges.map((change) => change.column))
    for (const column of DIAGNOSTIC_COLUMN_NAMES) {
      if (intended.has(column)) continue
      assert.deepEqual(
        canonical(after)[column],
        canonical(before as unknown as Record<string, unknown>)[column],
        `${column} unchanged`,
      )
    }
    assert.deepEqual(after.diagnostics, JSON.parse(JSON.stringify(documentOf(planned))))
  })
}

// ---------------------------------------------------------------------------
// The real `runUserFactsBackfill` loop, end to end on PGlite under the lock
// ---------------------------------------------------------------------------

const ARTIFACT_STUB = `
CREATE TABLE public.personal_plan_prepared_artifacts (
  id uuid PRIMARY KEY,
  lead_id uuid NOT NULL,
  user_id uuid,
  status text NOT NULL,
  created_at timestamptz NOT NULL,
  quiz_answers jsonb NOT NULL,
  canonical_profile jsonb NOT NULL
);
`

/** A PostgREST-shaped read client over PGlite — exactly the builder surface the backfill script
 * uses (`select`, `eq`, `in`, `gt`, `order`, `limit`, awaited) — plus the door's `rpc`. Values
 * come back as PostgREST serialises them (timestamps as ISO strings). */
function pgliteRestClient(pg: PersonalPlanTestDb) {
  const rpc = pgliteRpcClient(pg)
  const safe = (name: string) => {
    if (!/^[a-z_]+$/.test(name)) throw new Error(`unsupported identifier ${name}`)
    return name
  }
  return {
    rpc: rpc.rpc,
    from(table: string) {
      let columns = "*"
      const where: string[] = []
      const params: unknown[] = []
      let orderBy = ""
      let limit = ""
      const builder = {
        select(selected: string) {
          columns = selected
            .split(",")
            .map((column) => safe(column.trim()))
            // PostgREST serialises timestamptz with its microseconds; a JS Date would drop them.
            .map((column) =>
              column === "updated_at"
                ? `pg_catalog.to_json(updated_at) #>> '{}' AS updated_at`
                : column,
            )
            .join(", ")
          return builder
        },
        eq(column: string, value: unknown) {
          params.push(value)
          where.push(`${safe(column)}::text = $${params.length}::text`)
          return builder
        },
        in(column: string, values: unknown[]) {
          params.push(values.map(String))
          where.push(`${safe(column)}::text = ANY($${params.length}::text[])`)
          return builder
        },
        gt(column: string, value: unknown) {
          params.push(value)
          where.push(`${safe(column)}::text > $${params.length}::text`)
          return builder
        },
        order(column: string) {
          orderBy = ` ORDER BY ${safe(column)}`
          return builder
        },
        limit(count: number) {
          limit = ` LIMIT ${Number(count)}`
          return builder
        },
        then(
          resolve: (result: { data: unknown[]; error: null }) => unknown,
          reject: (e: unknown) => unknown,
        ) {
          const sql = `SELECT ${columns} FROM public.${safe(table)}${where.length ? ` WHERE ${where.join(" AND ")}` : ""}${orderBy}${limit}`
          return pg
            .query<Record<string, unknown>>(sql, params)
            .then(({ rows }) =>
              resolve({
                data: rows.map((dbRow) =>
                  Object.fromEntries(
                    Object.entries(dbRow).map(([key, value]) => [
                      key,
                      value instanceof Date ? value.toISOString() : value,
                    ]),
                  ),
                ),
                error: null,
              }),
            )
            .catch(reject)
        },
      }
      return builder
    },
  }
}

test("the real runUserFactsBackfill loop on PGlite under the lock: dry-run report, --apply through the door, idempotent rerun", async (t) => {
  const pg = await mobileFactsDatabase(t, { lock: false })
  await pg.exec(ARTIFACT_STUB)

  const edited = id(3, 1) // legacy lead, Haar-Check edit
  const ios = id(3, 2) // legacy lead, iOS edit with a scanner_profile_edits record
  const paid = id(3, 3) // untouched paid row
  const single = id(3, 4) // two leads; the newest names one concern and no main problem
  for (const userId of [edited, ios, paid, single]) await insertProfile(pg, userId)

  const leadAt = "2026-07-01T09:00:00.000Z"
  for (const [userId, leadId] of [
    [edited, id(4, 1)],
    [ios, id(4, 2)],
  ]) {
    await pg.query(
      `INSERT INTO public.leads (id, email, quiz_answers, quiz_kind, status, user_id, created_at)
       VALUES ($1, 'lead@example.test', $2, 'legacy', 'linked', $3, $4)`,
      [leadId, JSON.stringify(LEAD_ANSWERS), userId, leadAt],
    )
  }
  await pg.query(
    `INSERT INTO public.personal_plan_prepared_artifacts
       (id, lead_id, user_id, status, created_at, quiz_answers, canonical_profile)
     VALUES ($1, $2, $3, 'attached', $4, $5, $6)`,
    [
      id(5, 3),
      id(4, 3),
      paid,
      ARTIFACT.createdAt,
      JSON.stringify(V3_ENVELOPE),
      JSON.stringify({ modelVersion: "personal_plan_canonical_v1", ...adaptedCanonical() }),
    ],
  )

  const { primary_concern: _pick, ...singleConcernAnswers } = LEAD_ANSWERS
  void _pick
  for (const [leadId, answers, createdAt] of [
    [id(4, 4), LEAD_ANSWERS, "2026-05-01T09:00:00.000Z"],
    [id(4, 5), { ...singleConcernAnswers, concerns: ["tangling"] }, leadAt],
  ] as const) {
    await pg.query(
      `INSERT INTO public.leads (id, email, quiz_answers, quiz_kind, status, user_id, created_at)
       VALUES ($1, 'lead@example.test', $2, 'legacy', 'linked', $3, $4)`,
      [leadId, JSON.stringify(answers), single, createdAt],
    )
  }

  await seedLegacyRow(pg, edited, { ...LEAD_COLUMNS, hair_texture: "wavy" })
  await seedLegacyRow(pg, ios, { ...LEAD_COLUMNS, thickness: "fine" })
  await seedLegacyRow(pg, paid, PAID_COLUMNS)
  // primary_concern NULL: the column is younger than her quiz link.
  await seedLegacyRow(pg, single, {
    ...LEAD_COLUMNS,
    concerns: ["tangling"],
    primary_concern: null,
  })
  // The iOS edit: its context version's created_at is the edit time.
  const versionId = id(6, 2)
  await pg.query(
    `INSERT INTO public.scanner_context_versions
       (id, user_id, source_revision, profile_revision, source_hash, engine_version, snapshot_source,
        input_snapshot, output_snapshot, created_at)
     VALUES ($1, $2, 1, 1, $3, 'v1', 'initial', '{}', '{}', '2026-09-20T08:00:00.000Z')`,
    [versionId, ios, "a".repeat(64)],
  )
  await pg.query(
    `INSERT INTO public.scanner_profile_edits (user_id, profile_revision, context_version_id, quiz_answers, profile_snapshot)
     VALUES ($1, 1, $2, '{}', $3)`,
    [ios, versionId, JSON.stringify({ ...IOS_SNAPSHOT, user_id: ios })],
  )
  await applyUserFactsLock(pg)

  const client = pgliteRestClient(pg)
  const dryLines: string[] = []
  const dry = await runUserFactsBackfill([], {
    supabase: client as never,
    now: NOW,
    log: (line) => dryLines.push(line),
  })
  // `PRINT_BACKFILL_REPORT=1` prints the fixture report (the sample the owner signs off).
  if (process.env.PRINT_BACKFILL_REPORT) console.log(dryLines.join("\n"))
  assert.equal(dry.usersExamined, 4)
  assert.equal(dry.handEditedRows, 2)
  assert.equal(dry.ambiguousRows, 0)
  // The loader's "2 legacy leads" is informational: a note, not a skip.
  assert.equal(dry.skipped, 0)
  assert.equal(dry.notes, 1)
  assert.ok(
    dryLines.includes(
      `  ${"rows with hand-edited groups".padEnd(42)} 2 (structure 1, thickness 1)`,
    ),
  )
  // Both candidate times are printed beside the chosen one (I3).
  assert.ok(
    dryLines.includes(
      `  ${ios} [legacy_lead ${id(4, 2)}] thickness — editedAt 2026-09-20T08:00:00.000Z (iOS edit; candidates: iOS edit 2026-09-20T08:00:00.000Z, quiz taken + 1 ms 2026-07-01T09:00:00.001Z)`,
    ),
  )
  assert.ok(
    dryLines.includes(
      `  ${edited} [legacy_lead ${id(4, 1)}] structure — editedAt 2026-07-01T09:00:00.001Z (quiz taken + 1 ms; candidates: iOS edit none, quiz taken + 1 ms 2026-07-01T09:00:00.001Z)`,
    ),
  )
  assert.ok(dryLines.includes("    hair_texture: column=wavy old writer=curly"))
  assert.ok(
    dryLines.includes(
      "    diagnostics.goals: less_frizz,moisture,healthy_scalp,shine -> moisture,shine",
    ),
  )
  // The pattern table comes before the per-row sections; the only-concern fill is one line.
  const patternsAt = dryLines.findIndex((line) => line.startsWith("CHANGE PATTERNS ("))
  assert.ok(
    patternsAt > 0 &&
      patternsAt <
        dryLines.indexOf(dryLines.find((line) => line.startsWith("HAND-EDITED GROUPS"))!),
  )
  const patternRows = dryLines
    .slice(
      patternsAt + 1,
      dryLines.findIndex((line, index) => index > patternsAt && line === ""),
    )
    .map((line) => line.trim().replace(/\s+(\d+)$/, " | $1"))
  assert.deepEqual(patternRows, [
    "diagnostics.goals: healthy_scalp,less_frizz,moisture,shine -> moisture,shine | 1",
    "diagnostics.primary_concern: NULL -> her only concern (the door names it the main problem) | 1",
  ])
  assert.ok(
    dryLines.includes(
      `  ${single}: 2 legacy leads; the newest by quiz time competes, the older ones are fallbacks`,
    ),
  )
  assert.ok(dryLines.includes("SKIPPED (0)"))
  const before = await readRow(pg, edited)
  assert.equal(before?.facts_revision, 0, "a dry run writes nothing")

  const applyLines: string[] = []
  const applied = await runUserFactsBackfill(["--apply"], {
    supabase: client as never,
    now: NOW,
    log: (line) => applyLines.push(line),
  })
  assert.equal(applied.failures.length, 0, JSON.stringify(applied.failures))
  assert.equal(applied.applied, applied.writesPlanned)

  const editedRow = (await readRow(pg, edited))!
  assert.equal(editedRow.hair_texture, "wavy", "the hand edit survives the backfill")
  assert.equal(editedRow.thickness, "coarse")
  const provenance = editedRow.facts_provenance as { diagnostics: DomainProvenance }
  assert.deepEqual(provenance.diagnostics.fields, { texture: "user" })
  const iosRow = (await readRow(pg, ios))!
  assert.equal(iosRow.thickness, "fine")
  assert.equal(
    (iosRow.facts_provenance as { diagnostics: DomainProvenance }).diagnostics.editedAt,
    "2026-09-20T08:00:00.000Z",
  )
  const paidRow = (await readRow(pg, paid))!
  assert.deepEqual([...(paidRow.goals as string[])].sort(), ["moisture", "shine"])
  assert.ok(paidRow.quiz_context)

  const rerun = await runUserFactsBackfill(["--apply"], {
    supabase: client as never,
    now: NOW,
    log: () => {},
  })
  assert.equal(rerun.writesPlanned, 0, "idempotent: every domain already holds a document")
})

test("--catch-up on PGlite (I2): apply an untouched paid row, one live thickness write, catch-up -> only thickness is an edit", async (t) => {
  // Rollout order: backfill -> (legacy writers still live) -> catch-up -> deploy -> lock last.
  const pg = await mobileFactsDatabase(t, { lock: false })
  await pg.exec(ARTIFACT_STUB)
  const paid = id(8, 1)
  await insertProfile(pg, paid)
  await pg.query(
    `INSERT INTO public.personal_plan_prepared_artifacts
       (id, lead_id, user_id, status, created_at, quiz_answers, canonical_profile)
     VALUES ($1, $2, $3, 'attached', $4, $5, $6)`,
    [
      id(9, 1),
      id(9, 2),
      paid,
      ARTIFACT.createdAt,
      JSON.stringify(V3_ENVELOPE),
      JSON.stringify({ modelVersion: "personal_plan_canonical_v1", ...adaptedCanonical() }),
    ],
  )
  await seedLegacyRow(pg, paid, PAID_COLUMNS)
  const client = pgliteRestClient(pg)

  const applied = await runUserFactsBackfill(["--apply"], {
    supabase: client as never,
    now: NOW,
    log: () => {},
  })
  assert.equal(applied.failures.length, 0, JSON.stringify(applied.failures))
  const afterApply = (await readRow(pg, paid))!
  assert.equal(
    afterApply.facts_provenance && "diagnostics" in (afterApply.facts_provenance as object),
    true,
  )

  // A still-live legacy writer (the pre-deploy iOS edit) changes one column directly.
  await pg.query(`UPDATE public.hair_profiles SET thickness = 'coarse' WHERE user_id = $1`, [paid])

  const lines: string[] = []
  const catchUp = await runUserFactsBackfill(["--apply", "--catch-up"], {
    supabase: client as never,
    now: "2026-10-02T12:00:00.000Z",
    log: (line) => lines.push(line),
  })
  assert.equal(catchUp.failures.length, 0, JSON.stringify(catchUp.failures))
  assert.equal(catchUp.writesPlanned, 1, "only diagnostics is re-planned")
  assert.equal(catchUp.handEditedRows, 1)
  assert.ok(lines.includes(`  ${"rows with hand-edited groups".padEnd(42)} 1 (thickness 1)`))

  const after = (await readRow(pg, paid))!
  const provenance = (after.facts_provenance as { diagnostics: DomainProvenance }).diagnostics
  assert.deepEqual(provenance.fields, { thickness: "user" })
  assert.equal(provenance.editedAt, NOW, "newer than the backfill's own write")
  assert.equal(after.thickness, "coarse")
  assert.deepEqual([...(after.goals as string[])].sort(), ["moisture", "shine"])
  const document = after.diagnostics as DiagnosticsV1
  assert.deepEqual(document.goals, ["moisture", "shine"], "the document's native goals")
  assert.equal(document.primaryConcern, "low_shine")
  assert.deepEqual(document.source.raw, V3_ENVELOPE)
})

test("fix round 6 (I1) on PGlite: a legacy write between the backfill's load and its write is a conflict — nothing written, reported, the rerun picks it up", async (t) => {
  // Rollout step 2: the deployed legacy writers still change columns without touching
  // facts_revision, so the revision alone cannot see them.
  const pg = await mobileFactsDatabase(t, { lock: false })
  await pg.exec(ARTIFACT_STUB)
  const paid = id(8, 2)
  await insertProfile(pg, paid)
  await pg.query(
    `INSERT INTO public.personal_plan_prepared_artifacts
       (id, lead_id, user_id, status, created_at, quiz_answers, canonical_profile)
     VALUES ($1, $2, $3, 'attached', $4, $5, $6)`,
    [
      id(9, 3),
      id(9, 4),
      paid,
      ARTIFACT.createdAt,
      JSON.stringify(V3_ENVELOPE),
      JSON.stringify({ modelVersion: "personal_plan_canonical_v1", ...adaptedCanonical() }),
    ],
  )
  await seedLegacyRow(pg, paid, PAID_COLUMNS)

  const rest = pgliteRestClient(pg)
  let interleaved = false
  const racing = {
    ...rest,
    async rpc(name: string, args: Record<string, unknown>) {
      if (!interleaved) {
        interleaved = true
        // The legacy iOS edit lands after the page was loaded, before the first door call.
        await pg.query(`UPDATE public.hair_profiles SET thickness = 'coarse' WHERE user_id = $1`, [
          paid,
        ])
      }
      return rest.rpc(name, args)
    },
  }
  const lines: string[] = []
  const raced = await runUserFactsBackfill(["--apply"], {
    supabase: racing as never,
    now: NOW,
    log: (line) => lines.push(line),
  })
  assert.equal(raced.failures.length, 0, JSON.stringify(raced.failures))
  assert.equal(raced.applied, 0)
  assert.equal(raced.revisionConflicts, 1)
  assert.ok(
    lines.some(
      (line) =>
        line.startsWith(`    ${paid} diagnostics: updated_at changed since the load`) &&
        line.includes("left for the next run"),
    ),
    lines.filter((line) => line.includes(paid)).join("\n"),
  )
  const untouched = (await readRow(pg, paid))!
  assert.equal(untouched.facts_revision, 0, "nothing written")
  assert.equal(untouched.diagnostics, null)
  assert.equal(untouched.quiz_context, null)
  assert.equal(untouched.thickness, "coarse", "the legacy write stands")

  // The rerun loads the new state: the thickness write is a hand edit and survives; every write
  // carries the updated_at it was loaded with (or the previous write's).
  const calls: Record<string, unknown>[] = []
  const recording = {
    ...rest,
    async rpc(name: string, args: Record<string, unknown>) {
      calls.push(args)
      return rest.rpc(name, args)
    },
  }
  const rerun = await runUserFactsBackfill(["--apply"], {
    supabase: recording as never,
    now: NOW,
    log: () => {},
  })
  assert.equal(rerun.failures.length, 0, JSON.stringify(rerun.failures))
  assert.equal(rerun.revisionConflicts, 0)
  assert.equal(rerun.applied, rerun.writesPlanned)
  assert.ok(calls.length >= 2)
  for (const call of calls) assert.equal(typeof call.p_expected_updated_at, "string")
  const written = (await readRow(pg, paid))!
  assert.equal(written.thickness, "coarse")
  assert.deepEqual(
    (written.facts_provenance as { diagnostics: DomainProvenance }).diagnostics.fields,
    { thickness: "user" },
  )
})

test("fix round 6 (I3) on PGlite: backfill artifact A, link a newer lead B through the legacy columns, --catch-up -> B's diagnostics and A's context cleared", async (t) => {
  const pg = await mobileFactsDatabase(t, { lock: false })
  await pg.exec(ARTIFACT_STUB)
  const user = id(8, 3)
  await insertProfile(pg, user)
  await pg.query(
    `INSERT INTO public.personal_plan_prepared_artifacts
       (id, lead_id, user_id, status, created_at, quiz_answers, canonical_profile)
     VALUES ($1, $2, $3, 'attached', $4, $5, $6)`,
    [
      id(9, 5),
      id(9, 6),
      user,
      ARTIFACT.createdAt,
      JSON.stringify(V3_ENVELOPE),
      JSON.stringify({ modelVersion: "personal_plan_canonical_v1", ...adaptedCanonical() }),
    ],
  )
  await seedLegacyRow(pg, user, PAID_COLUMNS)
  const client = pgliteRestClient(pg)
  const applied = await runUserFactsBackfill(["--apply"], {
    supabase: client as never,
    now: NOW,
    log: () => {},
  })
  assert.equal(applied.failures.length, 0, JSON.stringify(applied.failures))
  assert.ok((await readRow(pg, user))!.quiz_context, "baseline: A's context stored")

  // Main's legacy link of lead B (taken after A), still deployed: it writes the columns directly.
  const leadB = id(4, 7)
  await pg.query(
    `INSERT INTO public.leads (id, email, quiz_answers, quiz_kind, status, user_id, created_at)
     VALUES ($1, 'lead@example.test', $2, 'legacy', 'linked', $3, '2026-09-10T09:00:00.000Z')`,
    [leadB, JSON.stringify(LEAD_ANSWERS), user],
  )
  await pg.query(
    `UPDATE public.hair_profiles
        SET hair_texture = 'curly', thickness = 'coarse', density = 'high', hair_length = 'medium',
            cuticle_condition = 'rough', protein_moisture_balance = 'snaps',
            chemical_treatment = '{natural}', scalp_type = 'dry', scalp_condition = 'dry_flakes',
            concerns = '{dryness,tangling}', primary_concern = 'tangling',
            goals = '{moisture,curl_definition}', desired_volume = NULL
      WHERE user_id = $1`,
    [user],
  )

  const lines: string[] = []
  const catchUp = await runUserFactsBackfill(["--apply", "--catch-up"], {
    supabase: client as never,
    now: "2026-10-02T12:00:00.000Z",
    log: (line) => lines.push(line),
  })
  assert.equal(catchUp.failures.length, 0, JSON.stringify(catchUp.failures))
  assert.deepEqual(catchUp.writesByDomain, { diagnostics: 1, quiz_context: 1 })
  assert.ok(
    lines.some((line) =>
      line.includes(
        `quiz_context: catch-up — legacy lead ${leadB} (2026-09-10T09:00:00.000Z) now wins over the stored artifact`,
      ),
    ),
    lines.join("\n"),
  )
  const after = (await readRow(pg, user))!
  const document = after.diagnostics as DiagnosticsV1
  assert.equal(document.source.kind, "legacy_quiz")
  assert.equal(document.source.leadId, leadB)
  assert.equal(after.hair_texture, "curly")
  assert.deepEqual(after.quiz_context, {}, "A's quiz context is cleared")
  assert.deepEqual(
    (after.facts_provenance as { quiz_context: DomainProvenance }).quiz_context.source,
    { kind: "legacy_lead", id: leadB },
  )

  // Idempotent: the next catch-up finds nothing to do.
  const again = await runUserFactsBackfill(["--apply", "--catch-up"], {
    supabase: client as never,
    now: "2026-10-03T12:00:00.000Z",
    log: () => {},
  })
  assert.equal(again.writesPlanned, 0)
})

test("fix round 7 (A) on PGlite: the catch-up's context write fails once — the rerun brings the context to B's target, diagnostics untouched; then nothing", async (t) => {
  const pg = await mobileFactsDatabase(t, { lock: false })
  await pg.exec(ARTIFACT_STUB)
  const user = id(8, 4)
  await insertProfile(pg, user)
  await pg.query(
    `INSERT INTO public.personal_plan_prepared_artifacts
       (id, lead_id, user_id, status, created_at, quiz_answers, canonical_profile)
     VALUES ($1, $2, $3, 'attached', $4, $5, $6)`,
    [
      id(9, 7),
      id(9, 8),
      user,
      ARTIFACT.createdAt,
      JSON.stringify(V3_ENVELOPE),
      JSON.stringify({ modelVersion: "personal_plan_canonical_v1", ...adaptedCanonical() }),
    ],
  )
  await seedLegacyRow(pg, user, PAID_COLUMNS)
  const client = pgliteRestClient(pg)
  const applied = await runUserFactsBackfill(["--apply"], {
    supabase: client as never,
    now: NOW,
    log: () => {},
  })
  assert.equal(applied.failures.length, 0, JSON.stringify(applied.failures))
  const contextA = (await readRow(pg, user))!.quiz_context as Record<string, unknown>
  assert.ok(Object.keys(contextA ?? {}).length > 0, "baseline: A's context with answers stored")

  // Main's legacy link of lead B (taken after A), still deployed: it writes the columns directly.
  const leadB = id(4, 8)
  await pg.query(
    `INSERT INTO public.leads (id, email, quiz_answers, quiz_kind, status, user_id, created_at)
     VALUES ($1, 'lead@example.test', $2, 'legacy', 'linked', $3, '2026-09-10T09:00:00.000Z')`,
    [leadB, JSON.stringify(LEAD_ANSWERS), user],
  )
  await pg.query(
    `UPDATE public.hair_profiles
        SET hair_texture = 'curly', thickness = 'coarse', density = 'high', hair_length = 'medium',
            cuticle_condition = 'rough', protein_moisture_balance = 'snaps',
            chemical_treatment = '{natural}', scalp_type = 'dry', scalp_condition = 'dry_flakes',
            concerns = '{dryness,tangling}', primary_concern = 'tangling',
            goals = '{moisture,curl_definition}', desired_volume = NULL
      WHERE user_id = $1`,
    [user],
  )

  // The catch-up: B's diagnostics land, the context write fails once (an RPC error).
  let failed = false
  const failingOnce = {
    ...client,
    async rpc(name: string, args: Record<string, unknown>) {
      if (!failed && args.p_domain === "quiz_context") {
        failed = true
        return { data: null, error: { message: "injected quiz_context failure" } }
      }
      return client.rpc(name, args)
    },
  }
  const catchUp = await runUserFactsBackfill(["--apply", "--catch-up"], {
    supabase: failingOnce as never,
    now: "2026-10-02T12:00:00.000Z",
    log: () => {},
  })
  assert.equal(failed, true, "the context write was attempted and failed")
  assert.deepEqual(
    catchUp.failures.map((failure) => failure.domain),
    ["quiz_context"],
    JSON.stringify(catchUp.failures),
  )
  const halfway = (await readRow(pg, user))!
  assert.equal((halfway.diagnostics as DiagnosticsV1).source.leadId, leadB)
  assert.deepEqual(halfway.quiz_context, contextA, "A's context still next to B's diagnostics")

  // Plain rerun: the context domain is decided on its own consistency — one write.
  const calls: Record<string, unknown>[] = []
  const recording = {
    ...client,
    async rpc(name: string, args: Record<string, unknown>) {
      calls.push(args)
      return client.rpc(name, args)
    },
  }
  const lines: string[] = []
  const rerun = await runUserFactsBackfill(["--apply"], {
    supabase: recording as never,
    now: "2026-10-03T12:00:00.000Z",
    log: (line) => lines.push(line),
  })
  assert.equal(rerun.failures.length, 0, JSON.stringify(rerun.failures))
  assert.deepEqual(rerun.writesByDomain, { quiz_context: 1 }, lines.join("\n"))
  assert.equal(rerun.applied, 1)
  assert.deepEqual(
    calls.map((call) => call.p_domain),
    ["quiz_context"],
    "exactly one door call",
  )
  assert.equal(calls[0]!.p_expected_revision, halfway.facts_revision, "CAS-pinned to the load")
  assert.equal(typeof calls[0]!.p_expected_updated_at, "string", "pinned to updated_at as well")
  const repaired = (await readRow(pg, user))!
  assert.deepEqual(repaired.quiz_context, {}, "a legacy lead carries no context: cleared")
  assert.deepEqual(
    (repaired.facts_provenance as { quiz_context: DomainProvenance }).quiz_context.source,
    { kind: "legacy_lead", id: leadB },
  )
  assert.deepEqual(repaired.diagnostics, halfway.diagnostics, "diagnostics untouched")
  assert.deepEqual(
    (repaired.facts_provenance as { diagnostics: DomainProvenance }).diagnostics,
    (halfway.facts_provenance as { diagnostics: DomainProvenance }).diagnostics,
    "diagnostics provenance untouched",
  )

  // Third run, in either mode: nothing left to do.
  for (const args of [["--apply"], ["--apply", "--catch-up"]]) {
    const third = await runUserFactsBackfill(args, {
      supabase: client as never,
      now: "2026-10-04T12:00:00.000Z",
      log: () => {},
    })
    assert.equal(third.writesPlanned, 0, `${args.join(" ")} plans nothing`)
  }
})

/** What the paid preparation stored as `canonical_profile`: the offer adapter over the answers. */
function adaptedCanonical(): Record<string, unknown> {
  return { ...adaptPersonalPlanAnswersForOffer(V3_ENVELOPE.answers as never).answers }
}
