import type { AppEventName } from "./events"

type AppEventRoute = {
  customerio: boolean
  meta: boolean
  posthog: boolean
}

export const eventRoutes = {
  chat_product_recommendation_shown: { customerio: true, meta: false, posthog: true },
  checkout_start_failed: { customerio: false, meta: false, posthog: true },
  checkout_prepared: { customerio: false, meta: false, posthog: true },
  checkout_preparation_outcome: { customerio: false, meta: false, posthog: true },
  checkout_started: { customerio: true, meta: true, posthog: true },
  first_chat_message: { customerio: true, meta: false, posthog: true },
  onboarding_completed: { customerio: true, meta: false, posthog: true },
  partner_access_activated: { customerio: false, meta: false, posthog: true },
  offer_chapter_revealed: { customerio: false, meta: false, posthog: true },
  offer_checkout_opened: { customerio: false, meta: true, posthog: true },
  offer_checkout_lifecycle: { customerio: false, meta: false, posthog: true },
  offer_cta_clicked: { customerio: false, meta: false, posthog: true },
  offer_detail_opened: { customerio: false, meta: false, posthog: true },
  // Customer.io delivery uses the server-side lead lookup in /api/analytics/offer-engaged.
  offer_engaged: { customerio: false, meta: false, posthog: true },
  offer_faq_opened: { customerio: false, meta: false, posthog: true },
  offer_payment_method_selected: { customerio: false, meta: false, posthog: true },
  offer_payment_option_viewed: { customerio: false, meta: false, posthog: true },
  offer_plan_selected: { customerio: false, meta: false, posthog: true },
  offer_section_viewed: { customerio: false, meta: false, posthog: true },
  offer_viewed: { customerio: false, meta: false, posthog: true },
  personal_plan_quiz_screen_viewed: { customerio: false, meta: false, posthog: true },
  personal_plan_result_reveal_completed: { customerio: false, meta: false, posthog: true },
  personal_plan_result_reveal_step_viewed: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_journey_started: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_routine_opened: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_review_viewed: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_review_back: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_review_completed: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_review_action: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_decision_selected: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_fallback_opened: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_flow_viewed: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_handoff: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_save_outcome: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_recovery_outcome: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_search_interacted: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_thumbnail_fallback: { customerio: false, meta: false, posthog: true },
  personal_plan_stage3_thumbnail_total_failure: { customerio: false, meta: false, posthog: true },
  personal_plan_stage4_editor_interacted: { customerio: false, meta: false, posthog: true },
  personal_plan_stage4_item_interacted: { customerio: false, meta: false, posthog: true },
  personal_plan_stage4_outcome: { customerio: false, meta: false, posthog: true },
  personal_plan_stage4_proposal_interacted: { customerio: false, meta: false, posthog: true },
  personal_plan_stage4_routine_viewed: { customerio: false, meta: false, posthog: true },
  pricing_viewed: { customerio: true, meta: true, posthog: true },
  purchase_completed: { customerio: false, meta: true, posthog: false },
  quiz_analysis_commitment: { customerio: false, meta: false, posthog: true },
  quiz_completed: { customerio: true, meta: false, posthog: true },
  quiz_goals_selected: { customerio: true, meta: false, posthog: true },
  quiz_email_deliverability_rejected: { customerio: false, meta: false, posthog: true },
  quiz_lead_captured: { customerio: false, meta: true, posthog: true },
  quiz_started: { customerio: true, meta: true, posthog: true },
  quiz_step_viewed: { customerio: true, meta: false, posthog: true },
  scan_started: { customerio: false, meta: false, posthog: true },
  scan_decoded: { customerio: false, meta: false, posthog: true },
  scan_result_shown: { customerio: false, meta: false, posthog: true },
  scan_not_found: { customerio: false, meta: false, posthog: true },
  scan_submission_created: { customerio: false, meta: false, posthog: true },
  scan_fallback_search_used: { customerio: false, meta: false, posthog: true },
  scan_saved: { customerio: false, meta: false, posthog: true },
  scan_buy_clicked: { customerio: false, meta: false, posthog: true },
  subscription_started: { customerio: false, meta: true, posthog: false },
  waitlist_signup_completed: { customerio: false, meta: false, posthog: true },
  waitlist_survey_completed: { customerio: false, meta: false, posthog: true },
  waitlist_whatsapp_clicked: { customerio: false, meta: false, posthog: true },
} satisfies Record<AppEventName, AppEventRoute>
