"use client"

// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.
import OfferVariant0 from "./discovery-call-v1"
import OfferVariant1 from "./organic-plan-before-after-v1"
import OfferVariant2 from "./organic-plan-v1"
import OfferVariant3 from "./personal-plan-v1"
import OfferVariant4 from "./scan-regal-v1"

export const OFFER_VARIANTS = {
  "discovery-call-v1": OfferVariant0,
  "organic-plan-before-after-v1": OfferVariant1,
  "organic-plan-v1": OfferVariant2,
  "personal-plan-v1": OfferVariant3,
  "scan-regal-v1": OfferVariant4,
} as const
