"use client"

// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.
import OfferVariant0 from "./default"
import OfferVariant1 from "./social-proof-below"

export const OFFER_VARIANTS = {
  default: OfferVariant0,
  "social-proof-below": OfferVariant1,
} as const
