export const PERSONAL_PLAN_FIELD_TEST_CAMPAIGN_TTL_DAYS = 30
export const PERSONAL_PLAN_FIELD_TEST_CAMPAIGN_MAX_ACTIVATIONS = 100
export const PERSONAL_PLAN_FIELD_TEST_ACCESS_DURATION_HOURS = 168

export const PERSONAL_PLAN_FIELD_TEST_CAMPAIGN_COOKIE = "chaarlie_personal_plan_field_test"
export const PERSONAL_PLAN_FIELD_TEST_KIND = "field_test" as const

export const PERSONAL_PLAN_FIELD_TEST_CAMPAIGN_TTL_SECONDS =
  PERSONAL_PLAN_FIELD_TEST_CAMPAIGN_TTL_DAYS * 24 * 60 * 60
