// Planning-only synthetic examples. No requests, persistence, analytics or native changes.
const examples={
 repair:{title:'Repair-Pflege',definition:'Wie stark eine Formel auf strapazierte Längen ausgelegt ist.',stops:['niedrig','mittel','hoch'],product:1,target:2,productValue:'mittel',targetValue:'hoch',status:'Mit Einschränkung',kind:'ordered',note:'Repair-Pflege: Die Definition bleibt vollständig. „Mittel“ und „hoch“ sind vorhandene Kategorien, keine gemessene Wirksamkeit. Der Hinweis „Mit Einschränkung“ übernimmt den bestehenden Zeilenstatus.'},
 thickness:{title:'Haardicke',definition:'Für welche Haardicke die Formel ausgelegt ist.',stops:['fein','mittel','dick'],product:[0,1,2],target:0,productValue:'jede Haardicke',targetValue:'fein',status:'Deckt deine Haardicke ab',kind:'set',note:'Haardicke: „Jede“ bedeutet hier fein, mittel und dick. A zeigt diese Eignungsmenge, B fasst sie sprachlich zusammen. Kein Zahlenstrahl und keine Rangfolge von besser zu schlechter. „Dein Haar“ benennt hier die vorhandene Haardicke, kein Pflegeziel.'},
 weight:{title:'Pflegegewicht',definition:'Wie reichhaltig die Formel ist. Reichhaltige Pflege kann feines Haar beschweren.',stops:['leicht','mittel','reichhaltig'],product:0,target:0,productValue:'leicht',targetValue:'leicht',status:'Passt',kind:'ordered',note:'Pflegegewicht: Die mögliche Beschwerung feinen Haars bleibt genannt. Der Satzteil „Leicht legt wenig auf, reichhaltig legt mehr auf“ entfällt als zusätzliche Abstufungserklärung; diese echte Kürzung steht zur Auswahl. Produkt und Ziel liegen hier beide bei leicht, wie in der unveränderten Hintergrundtabelle.'}
};
const phones=[document.getElementById('phone-a'),document.getElementById('phone-b')];
function render(key){const e=examples[key];document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===key)));const isSet=e.kind==='set';
 const stops=e.stops.map((s,i)=>{const product=isSet?e.product.includes(i):e.product===i,target=e.target===i;const label=isSet?(target?'Dein Haar':''):(product&&target?'Produkt · Dein Ziel':product?'Produkt':target?'Dein Ziel':'');return `<div class="stop">${!isSet?`<div class="stop-label ${target?'target':''}">${label}</div>`:''}<div class="stop-value ${product?'product':''} ${target?'target':''}">${s}</div>${isSet?`<div class="stop-label target">${label}</div>`:''}</div>`}).join('');
 phones[0].querySelector('.card-scroll').innerHTML=`<h3>${e.title}</h3><p class="definition">${e.definition}</p>${isSet?'<div class="set-heading">Produkt geeignet für</div>':''}<div class="scale ${isSet?'set':''}">${stops}</div>`;
 phones[1].querySelector('.card-scroll').innerHTML=`<h3>${e.title}</h3><div class="pair ${isSet?'set-pair':''}"><div class="value-box"><span>Produkt${isSet?' für':''}</span><strong>${e.productValue}</strong></div><div class="value-box target"><span>${isSet?'Dein Haar':'Dein Ziel'}</span><strong>${e.targetValue}</strong></div></div><div class="signal ${isSet||e.status==='Passt'?'green':''}"><i aria-hidden="true"><b>${isSet||e.status==='Passt'?'✓':'!'}</b></i>${e.status}</div><p class="definition bottom">${e.definition}</p>`;
 document.getElementById('case-note').textContent=e.note;phones.forEach(p=>{p.classList.remove('closed');p.querySelector('.reopen').hidden=true;p.querySelector('.card-scroll').scrollTop=0});}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.case)));
document.getElementById('large').addEventListener('change',e=>{document.body.classList.toggle('large-preview',e.target.checked);phones.forEach(p=>p.classList.toggle('large',e.target.checked))});
phones.forEach(p=>{p.querySelector('.close').addEventListener('click',()=>{p.classList.add('closed');p.querySelector('.reopen').hidden=false});p.querySelector('.reopen').addEventListener('click',()=>{p.classList.remove('closed');p.querySelector('.reopen').hidden=true})});
render('repair');
