const cases={
 repair:{title:'Repair-Pflege',definition:'Wie stark eine Formel auf strapazierte Längen ausgelegt ist.',levels:['niedrig','mittel','hoch'],product:[1],target:2,pValue:'mittel',tValue:'hoch',set:false,note:'Repair-Pflege: Produkt mittel, dein Ziel hoch. Gefärbt ist jeweils die zugehörige Position – keine gefüllte Strecke und keine Bewertung der Wirkung.'},
 weight:{title:'Pflegegewicht',definition:'Wie reichhaltig die Formel ist. Reichhaltige Pflege kann feines Haar beschweren.',levels:['leicht','mittel','reichhaltig'],product:[0],target:0,pValue:'leicht',tValue:'leicht',set:false,note:'Pflegegewicht: Produkt und Ziel liegen beide bei leicht. Beide Identitäten bleiben getrennt sichtbar; kein Marker verdeckt den anderen.'},
 thickness:{title:'Haardicke',definition:'Für welche Haardicke die Formel ausgelegt ist.',levels:['fein','mittel','dick'],product:[0,1,2],target:0,pValue:'jede',tValue:'fein',set:true,note:'Haardicke: Jede bedeutet die Eignungsmenge fein, mittel und dick. Alle drei Produktfelder sind belegt, dein Haar ist fein. Es gibt keine vierte Stufe „jede“.'}
};
const designs=[['Vergleichsmatrix','Gemeinsame Spalten, zwei klar benannte Zeilen.','Empfehlung','Werte lassen sich über dieselbe Spalte vergleichen. Auch mehrere passende Kategorien sind eindeutig.'],['Zwei Spuren','Identische Positionen, direkt beschriftete Werte.','','Mehr Platz für die Werte. Die Stufenbeschriftung gilt für beide Spuren.'],['Direkte Wertpaare','Zwei farblich klar getrennte Angaben.','','Am schnellsten zu lesen. Der vollständige Wertebereich wird bei ordinalen Eigenschaften nicht gezeigt.']];
const marker=kind=>`<i aria-hidden="true" class="${kind==='product'?'square':'circle'}"></i>`;
const rowName=(e,kind)=>kind==='product'?'Produkt':e.set?'Dein Haar':'Dein Ziel';
function cell(active,kind,label){return `<td class="${active?'active ':''}${kind}" aria-label="${label}: ${active?'ausgewählt':'nicht ausgewählt'}">${active?marker(kind):'<span class="empty" aria-hidden="true">—</span>'}</td>`}
function matrix(e){const heading=kind=>`<th scope="row" class="row-name ${kind}"><span class="name">${marker(kind)}${rowName(e,kind)}</span></th>`;return `<table class="matrix matrix-normal"><thead><tr><th aria-label="Vergleich"></th>${e.levels.map(l=>`<th scope="col">${l}</th>`).join('')}</tr></thead><tbody><tr>${heading('product')}${e.levels.map((l,i)=>cell(e.product.includes(i),'product',l)).join('')}</tr><tr>${heading('target')}${e.levels.map((l,i)=>cell(e.target===i,'target',l)).join('')}</tr></tbody></table><table class="matrix matrix-flipped"><thead><tr><th aria-label="Kategorie"></th><th scope="col" class="product">■ Produkt</th><th scope="col" class="target">● ${rowName(e,'target')}</th></tr></thead><tbody>${e.levels.map((l,i)=>`<tr><th scope="row" class="row-name">${l}</th>${cell(e.product.includes(i),'product',l)}${cell(e.target===i,'target',l)}</tr>`).join('')}</tbody></table>${e.set?'<p class="coverage-note">Produkt: jede Haardicke</p>':''}`}
function tracks(e){return ['product','target'].map(k=>`<div class="track-row ${k}"><div class="track-heading"><span>${marker(k)}${rowName(e,k)}</span><strong>${k==='product'?e.pValue:e.tValue}</strong></div><div class="track">${e.levels.map((l,i)=>`<div class="segment ${(k==='product'?e.product.includes(i):e.target===i)?'active':''} ${k}" aria-label="${l}: ${(k==='product'?e.product.includes(i):e.target===i)?'ausgewählt':'nicht ausgewählt'}">${(k==='product'?e.product.includes(i):e.target===i)?marker(k):''}</div>`).join('')}</div></div>`).join('')+`<div class="axis-labels">${e.levels.map(l=>`<span>${l==='reichhaltig'?'reich&shy;haltig':l}</span>`).join('')}</div>`}
function pairs(e){return `<div class="value-pair">${['product','target'].map(k=>`<div class="value-panel ${k}"><div class="value-heading">${marker(k)}${rowName(e,k)}</div><strong>${k==='product'?e.pValue:e.tValue}</strong>${e.set&&k==='product'?'<small>fein · mittel · dick</small>':''}</div>`).join('')}</div>`}
function render(key){const e=cases[key];document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===key)));document.getElementById('variants').innerHTML=designs.map((d,i)=>`<section class="variant" aria-label="Variante ${i+1}"><div class="variant-head"><h2><span>${i+1}</span>${d[0]}</h2><p>${d[1]} ${d[2]?`<span class="recommend">${d[2]}</span>`:''}</p></div><div class="crop"><div class="screen"><div class="shade"></div><div class="safe"><article class="card ${e.set?'is-set':''}" aria-label="Karte ${i+1}"><div class="scroll" tabindex="0"><h3 class="title">${e.title}</h3><p class="definition">${e.definition}</p>${[matrix,tracks,pairs][i](e)}</div><button class="close" aria-label="Erklärung ${i+1} schließen">×</button></article></div></div></div><p class="tradeoff">${d[3]}</p></section>`).join('');document.getElementById('case-note').textContent=e.note;document.querySelectorAll('.close').forEach(b=>b.addEventListener('click',()=>{b.closest('.card').hidden=true;document.getElementById('case-note').textContent='Für die erneute Vorschau oben ein Beispiel auswählen.'}));}
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.case)));
for(const name of ['large','narrow'])document.getElementById(name).addEventListener('change',e=>document.body.classList.toggle(name,e.target.checked));render('repair');
