import { createAdminClient } from "@/lib/supabase/admin"
import { generateEmbedding, generateEmbeddings } from "@/lib/openai/embeddings"
import { decomposeQuery } from "@/lib/rag/subquery-decomposer"
import { rerankWithCrossEncoder } from "@/lib/rag/reranker"
import { emitRetrievalEvent, topSourceTypes } from "@/lib/rag/retrieval-telemetry"
import {
  RRF_K,
  DENSE_CANDIDATE_COUNT,
  LEXICAL_CANDIDATE_COUNT,
  DENSE_MATCH_THRESHOLD,
  DEFAULT_FINAL_COUNT,
  RERANK_TOP_N,
  THICKNESS_MATCH_BOOST,
  SHAMPOO_CONCERN_MATCH_BOOST,
  COMMUNITY_QA_PRODUCT_BOOST,
} from "@/lib/rag/retrieval-constants"
import type { ContentChunk, IntentType, HairProfile } from "@/lib/types"

export interface RetrievedChunk extends ContentChunk {
  similarity: number
  weighted_similarity: number
  /** Which retrieval path produced this chunk */
  retrieval_path?: "dense" | "lexical" | "hybrid"
  /** Raw dense cosine similarity score */
  dense_score?: number
  /** Raw lexical BM25 rank score */
  lexical_score?: number
  /** RRF fused score (only present for hybrid path) */
  fused_score?: number
}

/** Intent → allowed source types. null = all sources. */
const INTENT_SOURCE_ROUTES: Record<IntentType, string[] | null> = {
  product_recommendation: ["product_list", "book", "community_qa"],
  ingredient_question: ["book", "qa"],
  hair_care_advice: ["book", "transcript", "qa", "product_list", "community_qa"],
  routine_help: ["book", "transcript", "qa", "product_list", "community_qa"],
  diagnosis: ["book", "qa", "live_call", "community_qa", "product_list"],
  general_chat: null,
  followup: null,
}

export interface RetrieveOptions {
  intent?: IntentType
  hairProfile?: HairProfile | null
  metadataFilter?: Record<string, string>
  shampooConcern?: string | null
  count?: number
  /** Subqueries generated by decomposition (skips decomposition if provided) */
  subqueries?: string[]
  /** Dense candidate count per subquery (default: DENSE_CANDIDATE_COUNT) */
  candidateCount?: number
  /** Whether to include keyword/lexical retrieval (default: true) */
  includeKeyword?: boolean
  /** Max candidates to send to reranker (default: RERANK_TOP_N) */
  rerankTopN?: number
  /** User ID for memory isolation filtering */
  userId?: string
}

export interface RetrieveContextDebug {
  subqueries: string[]
  source_types: string[] | null
  metadata_filter: Record<string, string> | null
  candidate_count_before_rerank: number
  reranked_count: number
  fallback_used: boolean
}

export interface RetrieveContextResult {
  chunks: RetrievedChunk[]
  debug: RetrieveContextDebug
}

// ── Internal types for RRF fusion ─────────────────────────────────────────────

interface DenseRow {
  id: string
  source_type: string
  source_name: string | null
  chunk_index: number | null
  content: string
  metadata: Record<string, unknown>
  similarity: number
  weighted_similarity: number
}

interface LexicalRow {
  id: string
  source_type: string
  source_name: string | null
  chunk_index: number | null
  content: string
  metadata: Record<string, unknown>
  rank: number
  weighted_rank: number
}

// ── Dense-only fallback (original retrieval path) ─────────────────────────────

async function retrieveDenseOnly(
  query: string,
  sourceTypes: string[] | null,
  metadataFilter: Record<string, string> | undefined,
): Promise<RetrievedChunk[]> {
  const embedding = await generateEmbedding(query)
  const supabase = createAdminClient()

  const { data, error } = await supabase.rpc("match_content_chunks", {
    query_embedding: embedding,
    match_count: DENSE_CANDIDATE_COUNT,
    match_threshold: DENSE_MATCH_THRESHOLD,
    source_filter: null,
    metadata_filter: metadataFilter ?? null,
    source_types: sourceTypes ?? null,
  })

  if (error) {
    console.error("Dense-only retrieval error:", error)
    return []
  }

  return ((data as DenseRow[]) ?? []).map((row) => ({
    ...row,
    token_count: null,
    created_at: "",
    retrieval_path: "dense" as const,
    dense_score: row.similarity,
  }))
}

// ── Hybrid retrieval: dense + lexical per subquery, then RRF ──────────────────

async function retrieveHybrid(
  query: string,
  subqueries: string[],
  sourceTypes: string[] | null,
  metadataFilter: Record<string, string> | undefined,
  candidateCount: number,
): Promise<RetrievedChunk[]> {
  const supabase = createAdminClient()

  // Generate embeddings for all subqueries in a single batch call
  const embeddings = await generateEmbeddings(subqueries)

  // For each subquery, run dense + lexical in parallel
  const allDenseResults: DenseRow[][] = []
  const allLexicalResults: LexicalRow[][] = []

  await Promise.all(
    subqueries.map(async (subquery, i) => {
      const [denseResult, lexicalResult] = await Promise.all([
        supabase.rpc("match_content_chunks", {
          query_embedding: embeddings[i],
          match_count: candidateCount,
          match_threshold: DENSE_MATCH_THRESHOLD,
          source_filter: null,
          metadata_filter: metadataFilter ?? null,
          source_types: sourceTypes ?? null,
        }),
        supabase.rpc("match_content_chunks_lexical", {
          query_text: subquery,
          match_count: LEXICAL_CANDIDATE_COUNT,
          source_filter: null,
          metadata_filter: metadataFilter ?? null,
          source_types: sourceTypes ?? null,
        }),
      ])

      if (denseResult.error) {
        console.error(`Dense retrieval failed for subquery ${i}:`, denseResult.error)
      }
      if (lexicalResult.error) {
        console.error(`Lexical retrieval failed for subquery ${i}:`, lexicalResult.error)
      }

      allDenseResults[i] = (denseResult.data as DenseRow[]) ?? []
      allLexicalResults[i] = (lexicalResult.data as LexicalRow[]) ?? []
    })
  )

  // ── RRF Fusion ────────────────────────────────────────────────────────────
  // For each chunk, accumulate 1/(k + rank) across all ranked lists.
  // Each subquery×retrieval_method pair is a separate ranked list.

  const chunkMap = new Map<string, {
    chunk: RetrievedChunk
    rrfScore: number
    bestDenseScore: number
    bestLexicalScore: number
  }>()

  // Process dense results
  for (const denseList of allDenseResults) {
    for (let rank = 0; rank < denseList.length; rank++) {
      const row = denseList[rank]
      const rrfContribution = 1 / (RRF_K + rank + 1) // 1-based rank

      const existing = chunkMap.get(row.id)
      if (existing) {
        existing.rrfScore += rrfContribution
        existing.bestDenseScore = Math.max(existing.bestDenseScore, row.similarity)
      } else {
        chunkMap.set(row.id, {
          chunk: {
            id: row.id,
            source_type: row.source_type,
            source_name: row.source_name,
            chunk_index: row.chunk_index,
            content: row.content,
            metadata: row.metadata,
            token_count: null,
            created_at: "",
            similarity: row.similarity,
            weighted_similarity: row.weighted_similarity,
            retrieval_path: "dense",
            dense_score: row.similarity,
          },
          rrfScore: rrfContribution,
          bestDenseScore: row.similarity,
          bestLexicalScore: 0,
        })
      }
    }
  }

  // Process lexical results
  for (const lexicalList of allLexicalResults) {
    for (let rank = 0; rank < lexicalList.length; rank++) {
      const row = lexicalList[rank]
      const rrfContribution = 1 / (RRF_K + rank + 1)

      const existing = chunkMap.get(row.id)
      if (existing) {
        existing.rrfScore += rrfContribution
        existing.bestLexicalScore = Math.max(existing.bestLexicalScore, row.rank)
        // Chunk found by both retrieval methods → mark as hybrid
        if (existing.chunk.retrieval_path === "dense") {
          existing.chunk.retrieval_path = "hybrid"
        }
      } else {
        chunkMap.set(row.id, {
          chunk: {
            id: row.id,
            source_type: row.source_type,
            source_name: row.source_name,
            chunk_index: row.chunk_index,
            content: row.content,
            metadata: row.metadata,
            token_count: null,
            created_at: "",
            similarity: 0,
            weighted_similarity: row.weighted_rank,
            retrieval_path: "lexical",
            lexical_score: row.rank,
          },
          rrfScore: rrfContribution,
          bestDenseScore: 0,
          bestLexicalScore: row.rank,
        })
      }
    }
  }

  // Build final array with fused scores
  const fused: RetrievedChunk[] = []
  for (const entry of chunkMap.values()) {
    const chunk = entry.chunk
    chunk.fused_score = entry.rrfScore
    chunk.dense_score = entry.bestDenseScore !== 0 ? entry.bestDenseScore : undefined
    chunk.lexical_score = entry.bestLexicalScore !== 0 ? entry.bestLexicalScore : undefined
    // Use RRF score as the sorting score
    chunk.weighted_similarity = entry.rrfScore
    fused.push(chunk)
  }

  // Sort by RRF fused score descending
  fused.sort((a, b) => (b.fused_score ?? 0) - (a.fused_score ?? 0))

  return fused
}

// ── Profile boost + deduplication (preserved from original) ───────────────────

export function computeChunkBoostedScore(
  chunk: Pick<RetrievedChunk, "metadata" | "source_type" | "weighted_similarity" | "similarity">,
  hairProfile: HairProfile | null | undefined,
  shampooConcern?: string | null,
): number {
  let score = chunk.weighted_similarity ?? chunk.similarity ?? 0

  if (
    hairProfile?.thickness &&
    chunk.metadata?.thickness === hairProfile.thickness
  ) {
    score *= THICKNESS_MATCH_BOOST
  }

  if (
    shampooConcern &&
    chunk.metadata?.concern === shampooConcern
  ) {
    score *= SHAMPOO_CONCERN_MATCH_BOOST
  }

  if (
    chunk.source_type === "community_qa" &&
    Array.isArray(chunk.metadata?.products_mentioned) &&
    (chunk.metadata.products_mentioned as string[]).length > 0
  ) {
    score *= COMMUNITY_QA_PRODUCT_BOOST
  }

  return score
}

function applyProfileBoostAndDedup(
  chunks: RetrievedChunk[],
  hairProfile: HairProfile | null | undefined,
  shampooConcern: string | null | undefined,
  finalCount: number,
): RetrievedChunk[] {
  // Step 1: Profile boost
  const scored = chunks.map((chunk) => {
    const score = computeChunkBoostedScore(chunk, hairProfile, shampooConcern)
    return { ...chunk, weighted_similarity: score }
  })

  // Step 2: Sort by boosted score
  scored.sort((a, b) => b.weighted_similarity - a.weighted_similarity)

  // Step 3: Deduplicate — drop chunks where >80% of the shorter text
  // appears as a contiguous substring in the longer text
  const kept: RetrievedChunk[] = []
  for (const chunk of scored) {
    const isDuplicate = kept.some((existing) => {
      const shorter =
        chunk.content.length <= existing.content.length
          ? chunk.content
          : existing.content
      const longer =
        chunk.content.length > existing.content.length
          ? chunk.content
          : existing.content
      if (shorter.length === 0) return true
      const windowSize = Math.floor(shorter.length * 0.8)
      for (let i = 0; i <= shorter.length - windowSize; i++) {
        if (longer.includes(shorter.slice(i, i + windowSize))) {
          return true
        }
      }
      return false
    })
    if (!isDuplicate) {
      kept.push(chunk)
    }
    if (kept.length >= finalCount) break
  }

  return kept
}

// ── Main entry point ──────────────────────────────────────────────────────────

/**
 * Retrieves relevant content chunks using hybrid search (dense + lexical + RRF fusion),
 * cross-encoder reranking, intent-based routing, authority-weighted scoring,
 * profile boosts, and deduplication.
 *
 * Flow:
 * 1. Decompose query into subqueries (or use provided subqueries)
 * 2. Per subquery: run dense + lexical retrieval in parallel
 * 3. Fuse results via Reciprocal Rank Fusion (RRF, k=60)
 * 4. Rerank top candidates with Cohere cross-encoder
 * 5. Apply profile boosts + deduplication
 * 6. Return top `count` results
 *
 * On hybrid failure, falls back to dense-only retrieval (FR-11).
 */
export async function retrieveContext(
  query: string,
  options: RetrieveOptions = {},
): Promise<RetrieveContextResult> {
  const {
    intent,
    hairProfile,
    metadataFilter,
    shampooConcern,
    count = DEFAULT_FINAL_COUNT,
    subqueries: providedSubqueries,
    candidateCount = DENSE_CANDIDATE_COUNT,
    includeKeyword = true,
    rerankTopN = RERANK_TOP_N,
  } = options

  const sourceTypes = intent ? INTENT_SOURCE_ROUTES[intent] : null

  try {
    // Decompose query into subqueries (or use provided ones)
    const subqueries = providedSubqueries ?? await decomposeQuery(query)

    let candidates: RetrievedChunk[]
    const fallbackUsed = false

    if (includeKeyword) {
      // Hybrid path: dense + lexical + RRF
      const fusionStart = performance.now()
      candidates = await retrieveHybrid(
        query,
        subqueries,
        sourceTypes,
        metadataFilter,
        candidateCount,
      )
      emitRetrievalEvent({
        event: "retrieval_fused",
        intent,
        candidate_count: candidates.length,
        stage_latency_ms: Math.round(performance.now() - fusionStart),
        top_source_types: topSourceTypes(candidates),
        subquery_count: subqueries.length,
      })
    } else {
      // Dense-only (explicit opt-out from keyword search)
      const denseStart = performance.now()
      candidates = await retrieveDenseOnly(query, sourceTypes, metadataFilter)
      emitRetrievalEvent({
        event: "retrieval_dense_completed",
        intent,
        candidate_count: candidates.length,
        stage_latency_ms: Math.round(performance.now() - denseStart),
        top_source_types: topSourceTypes(candidates),
      })
    }

    // Rerank top candidates with cross-encoder
    const { chunks: reranked, latencyMs: rerankLatency } =
      await rerankWithCrossEncoder(query, candidates, rerankTopN)
    emitRetrievalEvent({
      event: "retrieval_reranked",
      intent,
      candidate_count: reranked.length,
      stage_latency_ms: rerankLatency,
      top_source_types: topSourceTypes(reranked.slice(0, count)),
    })

    return {
      chunks: applyProfileBoostAndDedup(reranked, hairProfile, shampooConcern, count),
      debug: {
        subqueries,
        source_types: sourceTypes,
        metadata_filter: metadataFilter ?? null,
        candidate_count_before_rerank: candidates.length,
        reranked_count: reranked.length,
        fallback_used: fallbackUsed,
      },
    }
  } catch (error) {
    // FR-11: Fail safe to dense-only retrieval
    console.error("Hybrid retrieval failed, falling back to dense-only:", error)
    emitRetrievalEvent({
      event: "retrieval_fallback_dense_only",
      intent,
      candidate_count: 0,
      stage_latency_ms: 0,
    })
    try {
      const candidates = await retrieveDenseOnly(query, sourceTypes, metadataFilter)
      return {
        chunks: applyProfileBoostAndDedup(candidates, hairProfile, shampooConcern, count),
        debug: {
          subqueries: providedSubqueries ?? [query],
          source_types: sourceTypes,
          metadata_filter: metadataFilter ?? null,
          candidate_count_before_rerank: candidates.length,
          reranked_count: candidates.length,
          fallback_used: true,
        },
      }
    } catch (fallbackError) {
      console.error("Dense-only fallback also failed:", fallbackError)
      return {
        chunks: [],
        debug: {
          subqueries: providedSubqueries ?? [query],
          source_types: sourceTypes,
          metadata_filter: metadataFilter ?? null,
          candidate_count_before_rerank: 0,
          reranked_count: 0,
          fallback_used: true,
        },
      }
    }
  }
}
