// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.
import LandingVariant0 from "./default"
import LandingVariant1 from "./organic-refresh"
import LandingVariant2 from "./personal-plan-quiz"

export const LANDING_VARIANTS = {
  default: LandingVariant0,
  "organic-refresh": LandingVariant1,
  "personal-plan-quiz": LandingVariant2,
} as const
