// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.
import LandingVariant0 from "./default"
import LandingVariant1 from "./personal-plan-quiz"

export const LANDING_VARIANTS = {
  default: LandingVariant0,
  "personal-plan-quiz": LandingVariant1,
} as const
