import { createHash } from "node:crypto"

/** Trusted exact owner decisions; source snapshots, not catalogue or pack verification. */
export const BOND_OWNER_REGISTRY = [
  {
    research_key: "P01",
    product_name: "OLAPLEX No.3PLUS Complete Repair Treatment",
    brand: "OLAPLEX",
    market: "DE",
    size: "100 ml source lead",
    source_version: "2026-09-30:R12",
    source_url: "https://olaplex.de/products/original-olaplex-n-3plus-complete-repair-treatment",
    raw_sha256: "9e801dd87d1033ebb223727270ae1dfd3d3c570df830ffee0d02a9e502bb08e4",
    normalized_sha256: "f46416be72085b4f7022400daacf8d4d298de519fd9ef1ad008adc9dcd685dce",
    normalized_ingredients: [
      "aqua (water, eau)",
      "cetearyl alcohol",
      "behentrimonium methosulfate",
      "bis-aminopropyl diglycol dimaleate",
      "hydroxypropyl starch phosphate",
      "propanediol",
      "distearyldimonium chloride",
      "behentrimonium chloride",
      "glycerin",
      "cetyl alcohol",
      "stearyl alcohol",
      "casalpinia spinosa fruit pod extract",
      "butyrospermum parkii (shea) butter",
      "helianthus annuus (sunflower) extract",
      "persea gratissima (avocado) oil",
      "cocos nucifera (coconut) oil",
      "rosmarinus officinalis (rosemary) leaf extract",
      "helianthus annuus (sunflower) sprout extract",
      "panthenol",
      "quaternium-91",
      "oryza sativa (rice) bran extract",
      "tribehenin",
      "caprylic/capric triglyceride",
      "ethylhexylglycerin",
      "hydroxypropyl guar hydroxypropyltrimonium chloride",
      "tocopherol",
      "olus oil (vegetable oil, huile végétale)",
      "caprylyl caprylate",
      "cetrimonium chloride",
      "sodium pca",
      "polyhydroxystearic acid",
      "polyester-37",
      "ethyl linoleate",
      "ethyl oleate",
      "cetrimonium methosulfate",
      "isopropyl alcohol",
      "propylene glycol",
      "c13-15 alkane",
      "guar hydroxypropyltrimonium chloride",
      "pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate",
      "acrylamidopropyltrimonium chloride/acrylamide copolymer",
      "phenethyl benzoate",
      "trisodium ethylenediamine disuccinate",
      "sodium metabisulfite",
      "citric acid",
      "phenoxyethanol",
      "sodium benzoate",
      "parfum (fragrance)",
      "linalyl acetate",
      "linalool",
      "hydroxycitronellal",
      "alpha-isomethyl ionone",
      "citronellol",
      "ci 19140 (yellow 5)",
      "ci 15985 (yellow 6)",
    ],
    technology_family: "sulfur_targeting_dimaleate",
    claim_trust_level: "high",
    trust_basis: "owner_anchor",
    policy_reference: "owner-review-2026-09-30:P01",
  },
  {
    research_key: "P02",
    product_name: "K18 Leave-In Molecular Repair Hair Mask",
    brand: "K18",
    market: "DE",
    size: "50 ml",
    source_version: "2026-09-30:R11",
    source_url:
      "https://k18-hair.de/k18-hair/k18-oil/Leave-In-Molecular-Repair-Hair-Mask-50ml.aspx",
    raw_sha256: "b5e8142fcd8f54ce4e23ca5d9204667d3df9ebeeacc51d3e32fd49c7f7ede9bc",
    normalized_sha256: "fb3bb64f17eaa4f63be6d86900a913c2f7f2a6775c4854eb5c5e40b397692773",
    normalized_ingredients: [
      "water (aqua) (eau)",
      "alcohol denat.",
      "propylene glycol",
      "cetearyl alcohol",
      "dicaprylyl ether",
      "cetyl esters",
      "behentrimonium chloride",
      "polysorbate 20",
      "sh-oligopeptide-78",
      "hydrolyzed wheat protein",
      "hydrolyzed wheat starch",
      "isopropyl alcohol",
      "tocopherol",
      "phenoxyethanol",
      "potassium sorbate",
      "citric acid",
      "fragrance (parfum)",
      "geraniol",
      "linalool",
      "hexyl cinnamal",
      "benzyl alcohol",
    ],
    technology_family: "designed_peptide",
    claim_trust_level: "high",
    trust_basis: "owner_anchor",
    policy_reference: "owner-review-2026-09-30:P02",
  },
  {
    research_key: "P03",
    product_name: "epres Bond Repair Treatment",
    brand: "epres",
    market: "DE/EU",
    size: "15 ml concentrate vial; starter/refill presentation not catalog-reconciled",
    source_version: "2026-09-30:R07",
    source_url: "https://epres.com/products/bond-repair-treatment",
    raw_sha256: "df67885977548ed909d06b732de76166b43b2514cff64b1240c5f73d77641106",
    normalized_sha256: "e921881bd4f21bb59f731c7f0fc1de697028bd6519cfa271a4aca1ccb75db0d2",
    normalized_ingredients: [
      "diethylhexyl maleate",
      "oleyl alcohol",
      "alcohol denat.",
      "stearamidopropyl dimethylamine",
    ],
    technology_family: "maleate_ester",
    claim_trust_level: "high",
    trust_basis: "owner_anchor",
    policy_reference: "owner-review-2026-09-30:P03",
  },
  {
    research_key: "P04",
    product_name: "Elvital Bond Repair Plus Keratin-Festigendes Pre-Shampoo",
    brand: "L’Oréal Paris",
    market: "DE",
    size: "200 ml",
    source_version: "2026-09-30:R01",
    source_url: "https://www.loreal-paris.de/elvital/bond-repair/rescue-pre-shampoo",
    raw_sha256: "482b3e1c0a5317613e0202b8156fdc00058e90d1366c83232fd3c286fc341c36",
    normalized_sha256: "e5e9b5e7c3d8882f12622bda11a67ace0ef1aeb37b9660bf881231966815ae00",
    normalized_ingredients: [
      "aqua / water",
      "cetearyl alcohol",
      "citric acid",
      "behentrimonium chloride",
      "arginine",
      "cetyl esters",
      "betaine",
      "glycerin",
      "hydroxypropyl guar",
      "hydroxycitronellal",
      "phenoxyethanol",
      "steareth-100",
      "peg-150/decyl alcohol/smdi copolymer",
      "ppg-1 trideceth-6",
      "aminopropyl dimethicone",
      "polyquaternium-37",
      "chlorhexidine digluconate",
      "limonene",
      "linalool",
      "pinene",
      "isopropyl alcohol",
      "isododecane",
      "propylene glycol",
      "propylene glycol dicaprylate/dicaprate",
      "carvone",
      "geranyl acetate",
      "acrylates/stearyl methacrylate copolymer",
      "sorbitan oleate",
      "bis(c13-15 alkoxy) pg-amodimethicone",
      "butyrospermum parkii butter / shea butter",
      "potassium hydroxide",
      "tetramethyl acetyloctahydronaphthalenes",
      "citrus limon peel oil",
      "edta",
      "hexyl cinnamal",
      "parfum / fragrance",
    ],
    technology_family: "acid_calcium_management",
    claim_trust_level: "medium",
    trust_basis: "owner_calibration",
    policy_reference: "owner-review-2026-09-30:P04",
  },
  {
    research_key: "P05",
    product_name: "Redken Acidic Bonding Concentrate Intensive Treatment",
    brand: "Redken",
    market: "DE",
    size: "190 ml",
    source_version: "2026-09-30:R09",
    source_url: "https://www.douglas.de/de/p/5011495045",
    raw_sha256: "1b7dde77c6067231ce009b330c2474d7f677edd08688471092589e94fd390c0b",
    normalized_sha256: "4a18ed3c6c724f3a79124871d2be9a576e5037ece1a8e90ad6cb5dbdf86c66cf",
    normalized_ingredients: [
      "aqua / water",
      "cetearyl alcohol",
      "glycerin",
      "behentrimonium chloride",
      "stearyl alcohol",
      "citric acid",
      "cetyl esters",
      "sodium citrate",
      "isopropyl alcohol",
      "parfum / fragrance",
      "phenoxyethanol",
      "polyquaternium-10",
      "polysorbate 20",
      "hydroxypropyl guar",
      "limonene",
      "linalool",
    ],
    technology_family: "acid_calcium_management",
    claim_trust_level: "medium",
    trust_basis: "owner_calibration",
    policy_reference: "owner-review-2026-09-30:P05",
  },
  {
    research_key: "P06",
    product_name: "OGX Bond Protein Repair Sealing Serum",
    brand: "OGX",
    market: "DE/EU",
    size: "50 ml",
    source_version: "2026-09-30:N03",
    source_url:
      "https://www.boozt.com/de/de/ogx/bond-repair-sealing-serum-50-ml_32962840/231199512",
    raw_sha256: "07cd0f0fe0a8764d9fb71c73c8857acf2bcf202006c198cde93637cf1b4b81e6",
    normalized_sha256: "d115187c9084ab3b81bbf13e7a0809d1427f5ce8cb8afd70f3fcca768a9689b0",
    normalized_ingredients: [
      "aqua",
      "glycerin",
      "parfum",
      "behentrimonium chloride",
      "polysorbate 20",
      "triticum vulgare protein",
      "hydroxypropylgluconamide",
      "hydroxypropylammonium gluconate",
      "hydrolyzed keratin",
      "tocopheryl acetate",
      "panthenol",
      "arginine",
      "triticum vulgare bran extract",
      "triticum vulgare germ extract",
      "triticum vulgare germ oil",
      "camellia oleifera seed oil",
      "guar hydroxypropyltrimonium chloride",
      "cetearyl nonanoate",
      "linoleic acid",
      "caprylyl glycol",
      "caprylic/capric triglyceride",
      "hydroxyacetophenone",
      "tocopherol",
      "hydroxyethylcellulose",
      "polyquaternium-10",
      "polysorbate 60",
      "1,2-hexanediol",
      "isopropyl alcohol",
      "citric acid",
      "disodium phosphate",
      "benzoic acid",
      "sodium phosphate",
      "potassium sorbate",
      "phenoxyethanol",
      "tartaric acid",
      "sodium benzoate",
      "alpha-isomethyl ionone",
    ],
    technology_family: "gluconamide_gluconate",
    claim_trust_level: "low",
    trust_basis: "owner_calibration",
    policy_reference: "owner-review-2026-09-30:P06",
  },
  {
    research_key: "P07",
    product_name: "Aveda Botanical Repair Bond-Building Pre-Shampoo Treatment",
    brand: "Aveda",
    market: "DE",
    size: "150 ml",
    source_version: "2026-09-30:R04",
    source_url: "https://www.aveda.de/product/botanical-repair-bond-building-pre-shampoo-treatment",
    raw_sha256: "3f6d3873570520d1ebaa558db7991cec7b05171a333737e6c5a471953455b0ab",
    normalized_sha256: "13715e76da3df36492e021fe9068510b02afb71873d2ce7ea0b2adafbd9527e1",
    normalized_ingredients: [
      "water aqua eau",
      "butylene glycol",
      "glycerin",
      "caprylic/capric triglyceride",
      "cetearyl alcohol",
      "polyglyceryl-10 pentaoleate",
      "hydroxypropylgluconamide",
      "persea gratissima (avocado) oil",
      "camellia oleifera seed oil",
      "plukenetia volubilis seed oil",
      "helianthus annuus (sunflower) seed oil",
      "tocopherol",
      "squalane",
      "ethylhexylglycerin",
      "behentrimonium chloride",
      "hydroxypropylammonium gluconate",
      "guar hydroxypropyltrimonium chloride",
      "polyacrylamidopropyltrimonium chloride",
      "octyldodecyl citrate crosspolymer",
      "behenyl alcohol",
      "lactic acid",
      "tartaric acid",
      "fragrance (parfum)",
      "linalool",
      "limonene",
      "citronellol",
      "hydroxycitronellal",
      "benzyl alcohol",
      "benzyl benzoate",
      "benzyl salicylate",
      "potassium sorbate",
      "sodium benzoate",
    ],
    technology_family: "gluconamide_gluconate",
    claim_trust_level: "low",
    trust_basis: "owner_calibration",
    policy_reference: "owner-review-2026-09-30:P07",
  },
  {
    research_key: "P08",
    product_name: "Kérastase Première Concentré Décalcifiant Ultra-Réparateur",
    brand: "Kérastase",
    market: "DE",
    size: "250ml local retailer research target",
    source_version: "2026-09-30:N01",
    source_url:
      "https://www.basler-beauty.de/marken/kerastase/kerastase-premiere-concentre-decalcifiant-ultra-reparateur-250-ml.html",
    raw_sha256: "2121d90642abc1e01c5238f3220bf661c05d190b40d4883ea7c848be0901dbf3",
    normalized_sha256: "ce2a560edbe517a3a4a2580f04d8b1ae6813176639525dac8bc2cee76b2fff6f",
    normalized_ingredients: [
      "aqua / water / eau",
      "glycerin",
      "propylene glycol",
      "glycine",
      "citric acid",
      "peg-40 hydrogenated castor oil",
      "sodium hydroxide",
      "parfum / fragrance",
      "cetrimonium chloride",
      "polysorbate 20",
      "polysorbate 80",
      "phenoxyethanol",
      "hydrolyzed vegetable protein pg-propyl silanetriol",
      "hydroxypropyl guar",
      "hydroxypropyl guar hydroxypropyltrimonium chloride",
      "quaternium-80",
      "limonene",
      "linalool",
      "sodium benzoate",
      "citral",
      "potassium sorbate",
    ],
    technology_family: "acid_calcium_management",
    claim_trust_level: "medium",
    trust_basis: "owner_calibration",
    policy_reference: "owner-review-2026-09-30:P08",
  },
] as const

export const BOND_DEFAULT_POLICY = "owner-default-policy-2026-10-01"
export const BOND_REFERENCE_KEYS = ["P01", "P02", "P03", "P04", "P06"] as const
export const BOND_REFERENCE_REGISTRY_SHA256 = createHash("sha256")
  .update(JSON.stringify(BOND_OWNER_REGISTRY))
  .digest("hex")
export const BOND_METHOD_PINS = {
  method_id: "bondbuilder-inci",
  method_version: "bondbuilder-inci-v0.4",
  standard_sha256: "031d32585ff0e2d5d1cdf77985d85188097fbf69354a4977eb93944ec2c93e10",
  runbook_sha256: "fbd5c07af51861ae1904bc6f8acb6809878e95840e87180c52bb9f4b1c4fb6c5",
  prompt_sha256: "de657611b3d98b45cd2febc10850491bef2b77fa21009a03491baeeb1b8a0fa3",
  blind_guide_sha256: "698ad9feec477547b82c5833ed8d3a17c4be57329ac05cdbbd4d07c02874d86e",
  reference_registry_sha256: BOND_REFERENCE_REGISTRY_SHA256,
} as const
